/* compiladorCachacaScript.java */
/* Generated By:JavaCC: Do not edit this line. compiladorCachacaScript.java */
public class compiladorCachacaScript implements compiladorCachacaScriptConstants {

  private static javax.swing.JTextArea txtCodigo;
  private static javax.swing.JTextArea txtSaida;
  private static compiladorCachacaScript parser = null;

  public static void main(String args[]) {
    javax.swing.SwingUtilities.invokeLater(new Runnable() {
      public void run() {
        criarEMostrarGUI();
      }
    });
  }

  private static void criarEMostrarGUI() {
    // Configuração da Janela Principal
    javax.swing.JFrame frame = new javax.swing.JFrame("CachaçaScript IDE");
    frame.setDefaultCloseOperation(javax.swing.JFrame.EXIT_ON_CLOSE);
    frame.setSize(800, 600);
    frame.setLayout(new java.awt.BorderLayout());

    // Componentes de Texto
    txtCodigo = new javax.swing.JTextArea(); // Onde o usuário digita o código
    txtSaida = new javax.swing.JTextArea();  // Onde aparecerão os erros ou sucesso
    txtSaida.setEditable(false);

    // Painel de Divisão (Código em cima, Saída embaixo)
    javax.swing.JSplitPane splitPane = new javax.swing.JSplitPane(
        javax.swing.JSplitPane.VERTICAL_SPLIT,
        new javax.swing.JScrollPane(txtCodigo),
        new javax.swing.JScrollPane(txtSaida)
    );
    splitPane.setDividerLocation(400);
    frame.add(splitPane, java.awt.BorderLayout.CENTER);

    // Botão de Compilar
    javax.swing.JButton btnCompilar = new javax.swing.JButton("Virar Dose (Compilar)");
    btnCompilar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent e) {
        executarCompilacao();
      }
    });
    
    javax.swing.JPanel painelSuperior = new javax.swing.JPanel();
    painelSuperior.add(btnCompilar);
    frame.add(painelSuperior, java.awt.BorderLayout.NORTH);

    frame.setVisible(true);
  }

  private static void ejecutarCompilacao() {
    txtSaida.setText(""); // Limpa a saída anterior
    String conteudo = txtCodigo.getText();
    java.io.StringReader sr = new java.io.StringReader(conteudo);

    // Inicializa ou reinicializa o parser do JavaCC com o texto da GUI
    if (parser == null) {
      parser = new compiladorCachacaScript(sr);
    } else {
      compiladorCachacaScript.ReInit(sr);
    }

    try {
      txtSaida.append("Lendo programa CachaçaScript da tela...\n");
      compiladorCachacaScript.Programa();
      txtSaida.append("Sucesso: Programa sintaticamente correto.\n");
    } 
    catch (ParseException e) {
      txtSaida.append("🍺 Opa! Parece que a cachaça subiu...\n");
      Token t = e.currentToken != null ? e.currentToken.next : null;
      if (t != null) {
        txtSaida.append("Erro sintático na linha " + t.beginLine + ", coluna " + t.beginColumn + "\n");
        txtSaida.append("Token problemático: " + t.image + "\n");
      }
      txtSaida.append("Detalhes: " + e.getMessage() + "\n");
    } 
    catch (TokenMgrError e) {
      txtSaida.append("🍺 Ih rapaz... serviram um caractere estranho no balcão.\n");
      txtSaida.append("Erro léxico: encontrei algo que não pertence à linguagem CachaçaScript.\n");
      txtSaida.append("Detalhes: " + e.getMessage() + "\n");
    }
  }

/* =========================================================
 * PROGRAMA
 * Um programa começa com abreAButelada, pode ter funções,
 * possui um bloco principal e termina com fechaAButelada.
 * ========================================================= */
  static final public void Programa() throws ParseException {
    jj_consume_token(INICIO_PROGRAMA);
    DeclFunListOpt();
    Bloco();
    jj_consume_token(FIM_PROGRAMA);
    jj_consume_token(0);
}

/* Lista opcional de declarações de função antes do bloco principal. */
  static final public void DeclFunListOpt() throws ParseException {
    label_1:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case FUNCAO:{
        ;
        break;
        }
      default:
        jj_la1[0] = jj_gen;
        break label_1;
      }
      DeclFun();
    }
}

/* =========================================================
 * BLOCO E LISTA DE COMANDOS
 * ========================================================= */

/* Bloco delimitado por abreBarril e fechaBarril. */
  static final public void Bloco() throws ParseException {
    jj_consume_token(DELIMITADOR_ESQ);
    ListaComandosOpt();
    jj_consume_token(DELIMITADOR_DIR);
}

/* Zero ou mais comandos dentro de um bloco. */
  static final public void ListaComandosOpt() throws ParseException {
    label_2:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case DELIMITADOR_ESQ:
      case PONTO_VIRG:
      case IMPRIME:
      case ENTRADA:
      case SE:
      case MARCA_SE:
      case ENQUANTO:
      case FAZ:
      case PARA:
      case RETORNO:
      case TIPO_INT:
      case TIPO_FLOAT:
      case TIPO_BOOL:
      case TIPO_STRING:
      case TIPO_VAR:
      case ID:{
        ;
        break;
        }
      default:
        jj_la1[1] = jj_gen;
        break label_2;
      }
      Comando();
    }
}

/* Um comando da linguagem. */
  static final public void Comando() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case TIPO_INT:
    case TIPO_FLOAT:
    case TIPO_BOOL:
    case TIPO_STRING:
    case TIPO_VAR:{
      Decl();
      jj_consume_token(PONTO_VIRG);
      break;
      }
    case ID:{
      StmtFromId();
      jj_consume_token(PONTO_VIRG);
      break;
      }
    case IMPRIME:
    case ENTRADA:{
      Io();
      jj_consume_token(PONTO_VIRG);
      break;
      }
    case SE:
    case MARCA_SE:{
      If();
      break;
      }
    case ENQUANTO:{
      While();
      break;
      }
    case FAZ:{
      RepeatUntil();
      break;
      }
    case PARA:{
      For();
      break;
      }
    case RETORNO:{
      Ret();
      jj_consume_token(PONTO_VIRG);
      break;
      }
    case DELIMITADOR_ESQ:{
      Bloco();
      break;
      }
    case PONTO_VIRG:{
      jj_consume_token(PONTO_VIRG);
      break;
      }
    default:
      jj_la1[2] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
}

/* =========================================================
 * DECLARAÇÕES
 * ========================================================= */

/* Declara variável tipada ou variável genérica garrafa. */
  static final public void Decl() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case TIPO_INT:
    case TIPO_FLOAT:
    case TIPO_BOOL:
    case TIPO_STRING:{
      Tipo();
      break;
      }
    case TIPO_VAR:{
      jj_consume_token(TIPO_VAR);
      break;
      }
    default:
      jj_la1[3] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    ListaDecl();
}

/* Lista de itens declarados separados por maisUmaDose. */
  static final public void ListaDecl() throws ParseException {
    ItemDecl();
    label_3:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case VIRGULA:{
        ;
        break;
        }
      default:
        jj_la1[4] = jj_gen;
        break label_3;
      }
      jj_consume_token(VIRGULA);
      ItemDecl();
    }
}

/* Item declarado: apenas nome ou nome com valor inicial. */
  static final public void ItemDecl() throws ParseException {
    jj_consume_token(ID);
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case ATRIBUICAO:{
      jj_consume_token(ATRIBUICAO);
      Expr();
      break;
      }
    default:
      jj_la1[5] = jj_gen;
      ;
    }
}

/* Tipos primitivos da linguagem. */
  static final public void Tipo() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case TIPO_INT:{
      jj_consume_token(TIPO_INT);
      break;
      }
    case TIPO_FLOAT:{
      jj_consume_token(TIPO_FLOAT);
      break;
      }
    case TIPO_BOOL:{
      jj_consume_token(TIPO_BOOL);
      break;
      }
    case TIPO_STRING:{
      jj_consume_token(TIPO_STRING);
      break;
      }
    default:
      jj_la1[6] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
}

/* =========================================================
 * COMANDOS INICIADOS POR ID
 * ========================================================= */

/* Um comando que começa com identificador. */
  static final public void StmtFromId() throws ParseException {
    jj_consume_token(ID);
    StmtIdSuffix();
}

/* Depois do ID, decide se é atribuição ou chamada de função. */
  static final public void StmtIdSuffix() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case ATRIBUICAO:{
      jj_consume_token(ATRIBUICAO);
      Expr();
      break;
      }
    case ABRE_PAR:{
      jj_consume_token(ABRE_PAR);
      ArgsOpt();
      jj_consume_token(FECHA_PAR);
      break;
      }
    default:
      jj_la1[7] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
}

/* =========================================================
 * ENTRADA E SAÍDA
 * ========================================================= */

/* Comando de impressão ou leitura. */
  static final public void Io() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case IMPRIME:{
      jj_consume_token(IMPRIME);
      jj_consume_token(ABRE_PAR);
      PrintList();
      jj_consume_token(FECHA_PAR);
      break;
      }
    case ENTRADA:{
      jj_consume_token(ENTRADA);
      jj_consume_token(ABRE_PAR);
      ReadList();
      jj_consume_token(FECHA_PAR);
      break;
      }
    default:
      jj_la1[8] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
}

/* Lista de expressões para impressão. */
  static final public void PrintList() throws ParseException {
    Expr();
    label_4:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case VIRGULA:{
        ;
        break;
        }
      default:
        jj_la1[9] = jj_gen;
        break label_4;
      }
      jj_consume_token(VIRGULA);
      Expr();
    }
}

/* Lista de identificadores para leitura. */
  static final public void ReadList() throws ParseException {
    jj_consume_token(ID);
    label_5:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case VIRGULA:{
        ;
        break;
        }
      default:
        jj_la1[10] = jj_gen;
        break label_5;
      }
      jj_consume_token(VIRGULA);
      jj_consume_token(ID);
    }
}

/* =========================================================
 * CONDICIONAL
 * ========================================================= */

/* Condicional com marcador opcional mestreAlambique. */
  static final public void If() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case MARCA_SE:{
      jj_consume_token(MARCA_SE);
      break;
      }
    default:
      jj_la1[11] = jj_gen;
      ;
    }
    jj_consume_token(SE);
    jj_consume_token(ABRE_PAR);
    Expr();
    jj_consume_token(FECHA_PAR);
    Bloco();
    ElseOpt();
}

/* Else opcional. */
  static final public void ElseOpt() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case SENAO:{
      jj_consume_token(SENAO);
      Bloco();
      break;
      }
    default:
      jj_la1[12] = jj_gen;
      ;
    }
}

/* =========================================================
 * LAÇOS
 * ========================================================= */

/* Laço while. */
  static final public void While() throws ParseException {
    jj_consume_token(ENQUANTO);
    jj_consume_token(ABRE_PAR);
    Expr();
    jj_consume_token(FECHA_PAR);
    Bloco();
}

/* Laço repeat-until. */
  static final public void RepeatUntil() throws ParseException {
    jj_consume_token(FAZ);
    Bloco();
    jj_consume_token(ATE);
    jj_consume_token(ABRE_PAR);
    Expr();
    jj_consume_token(FECHA_PAR);
    jj_consume_token(PONTO_VIRG);
}

/* Laço for. */
  static final public void For() throws ParseException {
    jj_consume_token(PARA);
    jj_consume_token(ABRE_PAR);
    ForInitOpt();
    jj_consume_token(PONTO_VIRG);
    ExprOpt();
    jj_consume_token(PONTO_VIRG);
    ForPostOpt();
    jj_consume_token(FECHA_PAR);
    Bloco();
}

/* Inicialização opcional do for. */
  static final public void ForInitOpt() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case TIPO_INT:
    case TIPO_FLOAT:
    case TIPO_BOOL:
    case TIPO_STRING:
    case TIPO_VAR:
    case ID:{
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case TIPO_INT:
      case TIPO_FLOAT:
      case TIPO_BOOL:
      case TIPO_STRING:
      case TIPO_VAR:{
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case TIPO_INT:
        case TIPO_FLOAT:
        case TIPO_BOOL:
        case TIPO_STRING:{
          Tipo();
          break;
          }
        case TIPO_VAR:{
          jj_consume_token(TIPO_VAR);
          break;
          }
        default:
          jj_la1[13] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
        ListaDecl();
        break;
        }
      case ID:{
        IdStmtCab();
        break;
        }
      default:
        jj_la1[14] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      break;
      }
    default:
      jj_la1[15] = jj_gen;
      ;
    }
}

/* Condição opcional do for. */
  static final public void ExprOpt() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case ABRE_PAR:
    case TRUE:
    case FALSE:
    case SUBTRACAO:
    case NEGACAO:
    case NUMERO_FLOAT:
    case NUMERO_INT:
    case STR:
    case ID:{
      Expr();
      break;
      }
    default:
      jj_la1[16] = jj_gen;
      ;
    }
}

/* Pós-execução opcional do for. */
  static final public void ForPostOpt() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case ID:{
      IdStmtCab();
      break;
      }
    default:
      jj_la1[17] = jj_gen;
      ;
    }
}

/* Atribuição ou chamada de função dentro do cabeçalho do for. */
  static final public void IdStmtCab() throws ParseException {
    jj_consume_token(ID);
    StmtIdSuffix();
}

/* =========================================================
 * FUNÇÕES E RETORNO
 * ========================================================= */

/* Declaração de função. */
  static final public void DeclFun() throws ParseException {
    jj_consume_token(FUNCAO);
    RetTipo();
    jj_consume_token(ID);
    jj_consume_token(ABRE_PAR);
    ParamsOpt();
    jj_consume_token(FECHA_PAR);
    Bloco();
}

/* Tipo de retorno: tipo primitivo ou semDose. */
  static final public void RetTipo() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case TIPO_INT:
    case TIPO_FLOAT:
    case TIPO_BOOL:
    case TIPO_STRING:{
      Tipo();
      break;
      }
    case VOID:{
      jj_consume_token(VOID);
      break;
      }
    default:
      jj_la1[18] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
}

/* Parâmetros opcionais. */
  static final public void ParamsOpt() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case TIPO_INT:
    case TIPO_FLOAT:
    case TIPO_BOOL:
    case TIPO_STRING:{
      Params();
      break;
      }
    default:
      jj_la1[19] = jj_gen;
      ;
    }
}

/* Lista de parâmetros separados por maisUmaDose. */
  static final public void Params() throws ParseException {
    Param();
    label_6:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case VIRGULA:{
        ;
        break;
        }
      default:
        jj_la1[20] = jj_gen;
        break label_6;
      }
      jj_consume_token(VIRGULA);
      Param();
    }
}

/* Um parâmetro possui tipo e nome. */
  static final public void Param() throws ParseException {
    Tipo();
    jj_consume_token(ID);
}

/* Retorno sem expressão ou com expressão. */
  static final public void Ret() throws ParseException {
    jj_consume_token(RETORNO);
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case ABRE_PAR:
    case TRUE:
    case FALSE:
    case SUBTRACAO:
    case NEGACAO:
    case NUMERO_FLOAT:
    case NUMERO_INT:
    case STR:
    case ID:{
      Expr();
      break;
      }
    default:
      jj_la1[21] = jj_gen;
      ;
    }
}

/* =========================================================
 * ARGUMENTOS DE FUNÇÃO
 * ========================================================= */

/* Lista opcional de argumentos. */
  static final public void ArgsOpt() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case ABRE_PAR:
    case TRUE:
    case FALSE:
    case SUBTRACAO:
    case NEGACAO:
    case NUMERO_FLOAT:
    case NUMERO_INT:
    case STR:
    case ID:{
      Expr();
      label_7:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case VIRGULA:{
          ;
          break;
          }
        default:
          jj_la1[22] = jj_gen;
          break label_7;
        }
        jj_consume_token(VIRGULA);
        Expr();
      }
      break;
      }
    default:
      jj_la1[23] = jj_gen;
      ;
    }
}

/* =========================================================
 * EXPRESSÕES
 * A ordem abaixo implementa a precedência dos operadores:
 * ||, &&, igualdade, relacionais, soma/subtração,
 * multiplicação/divisão, unários e primários.
 * ========================================================= */
  static final public void Expr() throws ParseException {
    ExprOr();
}

  static final public void ExprOr() throws ParseException {
    ExprAnd();
    label_8:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case OU_LOGICO:{
        ;
        break;
        }
      default:
        jj_la1[24] = jj_gen;
        break label_8;
      }
      jj_consume_token(OU_LOGICO);
      ExprAnd();
    }
}

  static final public void ExprAnd() throws ParseException {
    ExprEq();
    label_9:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case E_LOGICO:{
        ;
        break;
        }
      default:
        jj_la1[25] = jj_gen;
        break label_9;
      }
      jj_consume_token(E_LOGICO);
      ExprEq();
    }
}

  static final public void ExprEq() throws ParseException {
    ExprRel();
    label_10:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case IGUALDADE:
      case DIFERENTE:{
        ;
        break;
        }
      default:
        jj_la1[26] = jj_gen;
        break label_10;
      }
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case IGUALDADE:{
        jj_consume_token(IGUALDADE);
        break;
        }
      case DIFERENTE:{
        jj_consume_token(DIFERENTE);
        break;
        }
      default:
        jj_la1[27] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      ExprRel();
    }
}

  static final public void ExprRel() throws ParseException {
    ExprAdd();
    label_11:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case MENOR_IGUAL:
      case MAIOR_IGUAL:
      case MAIOR:
      case MENOR:{
        ;
        break;
        }
      default:
        jj_la1[28] = jj_gen;
        break label_11;
      }
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case MENOR:{
        jj_consume_token(MENOR);
        break;
        }
      case MAIOR:{
        jj_consume_token(MAIOR);
        break;
        }
      case MENOR_IGUAL:{
        jj_consume_token(MENOR_IGUAL);
        break;
        }
      case MAIOR_IGUAL:{
        jj_consume_token(MAIOR_IGUAL);
        break;
        }
      default:
        jj_la1[29] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      ExprAdd();
    }
}

  static final public void ExprAdd() throws ParseException {
    ExprMul();
    label_12:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case SOMA:
      case SUBTRACAO:{
        ;
        break;
        }
      default:
        jj_la1[30] = jj_gen;
        break label_12;
      }
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case SOMA:{
        jj_consume_token(SOMA);
        break;
        }
      case SUBTRACAO:{
        jj_consume_token(SUBTRACAO);
        break;
        }
      default:
        jj_la1[31] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      ExprMul();
    }
}

  static final public void ExprMul() throws ParseException {
    ExprUn();
    label_13:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case MULTIPLICACAO:
      case DIVISAO:{
        ;
        break;
        }
      default:
        jj_la1[32] = jj_gen;
        break label_13;
      }
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case MULTIPLICACAO:{
        jj_consume_token(MULTIPLICACAO);
        break;
        }
      case DIVISAO:{
        jj_consume_token(DIVISAO);
        break;
        }
      default:
        jj_la1[33] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      ExprUn();
    }
}

  static final public void ExprUn() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case NEGACAO:{
      jj_consume_token(NEGACAO);
      ExprUn();
      break;
      }
    case SUBTRACAO:{
      jj_consume_token(SUBTRACAO);
      ExprUn();
      break;
      }
    case ABRE_PAR:
    case TRUE:
    case FALSE:
    case NUMERO_FLOAT:
    case NUMERO_INT:
    case STR:
    case ID:{
      Prim();
      break;
      }
    default:
      jj_la1[34] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
}

/* Valor primário de uma expressão. */
  static final public void Prim() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case NUMERO_FLOAT:{
      jj_consume_token(NUMERO_FLOAT);
      break;
      }
    case NUMERO_INT:{
      jj_consume_token(NUMERO_INT);
      break;
      }
    case TRUE:{
      jj_consume_token(TRUE);
      break;
      }
    case FALSE:{
      jj_consume_token(FALSE);
      break;
      }
    case STR:{
      jj_consume_token(STR);
      break;
      }
    case ID:{
      jj_consume_token(ID);
      PrimIdSuffix();
      break;
      }
    case ABRE_PAR:{
      jj_consume_token(ABRE_PAR);
      Expr();
      jj_consume_token(FECHA_PAR);
      break;
      }
    default:
      jj_la1[35] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
}

/* Depois de um ID dentro de expressão, decide se é variável ou chamada. */
  static final public void PrimIdSuffix() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case ABRE_PAR:{
      jj_consume_token(ABRE_PAR);
      ArgsOpt();
      jj_consume_token(FECHA_PAR);
      break;
      }
    default:
      jj_la1[36] = jj_gen;
      ;
    }
}

  static private boolean jj_initialized_once = false;
  /** Generated Token Manager. */
  static public compiladorCachacaScriptTokenManager token_source;
  static SimpleCharStream jj_input_stream;
  /** Current token. */
  static public Token token;
  /** Next token. */
  static public Token jj_nt;
  static private int jj_ntk;
  static private int jj_gen;
  static final private int[] jj_la1 = new int[37];
  static private int[] jj_la1_0;
  static private int[] jj_la1_1;
  static {
	   jj_la1_init_0();
	   jj_la1_init_1();
	}
	private static void jj_la1_init_0() {
	   jj_la1_0 = new int[] {0x2000000,0xf5772200,0xf5772200,0xf0000000,0x8000,0x4000,0xf0000000,0x4800,0x30000,0x8000,0x8000,0x100000,0x80000,0xf0000000,0xf0000000,0xf0000000,0x800,0x0,0xf8000000,0xf0000000,0x8000,0x800,0x8000,0x800,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x800,0x800,0x800,};
	}
	private static void jj_la1_init_1() {
	   jj_la1_1 = new int[] {0x0,0x80001,0x80001,0x1,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x1,0x80001,0x80001,0xf8406,0x80000,0x0,0x0,0x0,0xf8406,0x0,0xf8406,0x100,0x80,0x60,0x60,0x6018,0x6018,0x600,0x600,0x1800,0x1800,0xf8406,0xf0006,0x0,};
	}

  /** Constructor with InputStream. */
  public compiladorCachacaScript(java.io.InputStream stream) {
	  this(stream, null);
  }
  /** Constructor with InputStream and supplied encoding */
  public compiladorCachacaScript(java.io.InputStream stream, String encoding) {
	 if (jj_initialized_once) {
	   System.out.println("ERROR: Second call to constructor of static parser.  ");
	   System.out.println("	   You must either use ReInit() or set the JavaCC option STATIC to false");
	   System.out.println("	   during parser generation.");
	   throw new Error();
	 }
	 jj_initialized_once = true;
	 try { jj_input_stream = new SimpleCharStream(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
	 token_source = new compiladorCachacaScriptTokenManager(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 37; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  static public void ReInit(java.io.InputStream stream) {
	  ReInit(stream, null);
  }
  /** Reinitialise. */
  static public void ReInit(java.io.InputStream stream, String encoding) {
	 try { jj_input_stream.ReInit(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
	 token_source.ReInit(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 37; i++) jj_la1[i] = -1;
  }

  /** Constructor. */
  public compiladorCachacaScript(java.io.Reader stream) {
	 if (jj_initialized_once) {
	   System.out.println("ERROR: Second call to constructor of static parser. ");
	   System.out.println("	   You must either use ReInit() or set the JavaCC option STATIC to false");
	   System.out.println("	   during parser generation.");
	   throw new Error();
	 }
	 jj_initialized_once = true;
	 jj_input_stream = new SimpleCharStream(stream, 1, 1);
	 token_source = new compiladorCachacaScriptTokenManager(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 37; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  static public void ReInit(java.io.Reader stream) {
	if (jj_input_stream == null) {
	   jj_input_stream = new SimpleCharStream(stream, 1, 1);
	} else {
	   jj_input_stream.ReInit(stream, 1, 1);
	}
	if (token_source == null) {
 token_source = new compiladorCachacaScriptTokenManager(jj_input_stream);
	}

	 token_source.ReInit(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 37; i++) jj_la1[i] = -1;
  }

  /** Constructor with generated Token Manager. */
  public compiladorCachacaScript(compiladorCachacaScriptTokenManager tm) {
	 if (jj_initialized_once) {
	   System.out.println("ERROR: Second call to constructor of static parser. ");
	   System.out.println("	   You must either use ReInit() or set the JavaCC option STATIC to false");
	   System.out.println("	   during parser generation.");
	   throw new Error();
	 }
	 jj_initialized_once = true;
	 token_source = tm;
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 37; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(compiladorCachacaScriptTokenManager tm) {
	 token_source = tm;
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 37; i++) jj_la1[i] = -1;
  }

  static private Token jj_consume_token(int kind) throws ParseException {
	 Token oldToken;
	 if ((oldToken = token).next != null) token = token.next;
	 else token = token.next = token_source.getNextToken();
	 jj_ntk = -1;
	 if (token.kind == kind) {
	   jj_gen++;
	   return token;
	 }
	 token = oldToken;
	 jj_kind = kind;
	 throw generateParseException();
  }

/** Get the next Token. */
  static final public Token getNextToken() {
	 if (token.next != null) token = token.next;
	 else token = token.next = token_source.getNextToken();
	 jj_ntk = -1;
	 jj_gen++;
	 return token;
  }

/** Get the specific Token. */
  static final public Token getToken(int index) {
	 Token t = token;
	 for (int i = 0; i < index; i++) {
	   if (t.next != null) t = t.next;
	   else t = t.next = token_source.getNextToken();
	 }
	 return t;
  }

  static private int jj_ntk_f() {
	 if ((jj_nt=token.next) == null)
	   return (jj_ntk = (token.next=token_source.getNextToken()).kind);
	 else
	   return (jj_ntk = jj_nt.kind);
  }

  static private java.util.List<int[]> jj_expentries = new java.util.ArrayList<int[]>();
  static private int[] jj_expentry;
  static private int jj_kind = -1;

  /** Generate ParseException. */
  static public ParseException generateParseException() {
	 jj_expentries.clear();
	 boolean[] la1tokens = new boolean[53];
	 if (jj_kind >= 0) {
	   la1tokens[jj_kind] = true;
	   jj_kind = -1;
	 }
	 for (int i = 0; i < 37; i++) {
	   if (jj_la1[i] == jj_gen) {
		 for (int j = 0; j < 32; j++) {
		   if ((jj_la1_0[i] & (1<<j)) != 0) {
			 la1tokens[j] = true;
		   }
		   if ((jj_la1_1[i] & (1<<j)) != 0) {
			 la1tokens[32+j] = true;
		   }
		 }
	   }
	 }
	 for (int i = 0; i < 53; i++) {
	   if (la1tokens[i]) {
		 jj_expentry = new int[1];
		 jj_expentry[0] = i;
		 jj_expentries.add(jj_expentry);
	   }
	 }
	 int[][] exptokseq = new int[jj_expentries.size()][];
	 for (int i = 0; i < jj_expentries.size(); i++) {
	   exptokseq[i] = jj_expentries.get(i);
	 }
	 return new ParseException(token, exptokseq, tokenImage);
  }

  static private boolean trace_enabled;

/** Trace enabled. */
  static final public boolean trace_enabled() {
	 return trace_enabled;
  }

  /** Enable tracing. */
  static final public void enable_tracing() {
  }

  /** Disable tracing. */
  static final public void disable_tracing() {
  }

}