/* compiladorCachacaScript.java */
/* Generated By:JavaCC: Do not edit this line. compiladorCachacaScript.java */
public class compiladorCachacaScript implements compiladorCachacaScriptConstants {
  public static void main(String args[])
  {
    CachacaScriptIDE.main(args);
  }

/* =========================================================
 * PROGRAMA
 * Um programa começa com abreAButelada, pode ter funções,
 * possui um bloco principal e termina com fechaAButelada.
 * ========================================================= */
  static final public ASTNode Programa() throws ParseException {ASTNode funs;
  ASTNode mainBlock;
    jj_consume_token(INICIO_PROGRAMA);
    funs = DeclFunListOpt();
    mainBlock = Bloco();
    jj_consume_token(FIM_PROGRAMA);
    jj_consume_token(0);
ASTNode node = new ASTNode("Programa (abreAButelada ... fechaAButelada)");
    node.addChild(funs);
    node.addChild(mainBlock);
    {if ("" != null) return node;}
    throw new Error("Missing return statement in function");
}

/* Lista opcional de declarações de função antes do bloco principal. */
  static final public ASTNode DeclFunListOpt() throws ParseException {ASTNode fun;
  ASTNode node;
node = new ASTNode("Lista de Fun\u00e7\u00f5es");
    label_1:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case FUNCAO:{
        ;
        break;
        }
      default:
        jj_la1[0] = jj_gen;
        break label_1;
      }
      fun = DeclFun();
node.addChild(fun);
    }
{if ("" != null) return node;}
    throw new Error("Missing return statement in function");
}

/* =========================================================
 * BLOCO E LISTA DE COMANDOS
 * ========================================================= */

/* Bloco delimitado por abreBarril e fechaBarril. */
  static final public ASTNode Bloco() throws ParseException {ASTNode cmds;
    jj_consume_token(DELIMITADOR_ESQ);
    cmds = ListaComandosOpt();
    jj_consume_token(DELIMITADOR_DIR);
ASTNode node = new ASTNode("Bloco (abreBarril ... fechaBarril)");
    node.addChild(cmds);
    {if ("" != null) return node;}
    throw new Error("Missing return statement in function");
}

/* Zero ou mais comandos dentro de um bloco. */
  static final public ASTNode ListaComandosOpt() throws ParseException {ASTNode cmd;
  ASTNode node;
node = new ASTNode("Comandos");
    label_2:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case DELIMITADOR_ESQ:
      case PONTO_VIRG:
      case IMPRIME:
      case ENTRADA:
      case SE:
      case MARCA_SE:
      case ENQUANTO:
      case FAZ:
      case PARA:
      case RETORNO:
      case TIPO_INT:
      case TIPO_FLOAT:
      case TIPO_BOOL:
      case TIPO_STRING:
      case TIPO_VAR:
      case ID:{
        ;
        break;
        }
      default:
        jj_la1[1] = jj_gen;
        break label_2;
      }
      cmd = Comando();
node.addChild(cmd);
    }
{if ("" != null) return node;}
    throw new Error("Missing return statement in function");
}

/* Um comando da linguagem. */
  static final public ASTNode Comando() throws ParseException {ASTNode c = null;
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case TIPO_INT:
    case TIPO_FLOAT:
    case TIPO_BOOL:
    case TIPO_STRING:
    case TIPO_VAR:{
      c = Decl();
      jj_consume_token(PONTO_VIRG);
      break;
      }
    case ID:{
      c = StmtFromId();
      jj_consume_token(PONTO_VIRG);
      break;
      }
    case IMPRIME:
    case ENTRADA:{
      c = Io();
      jj_consume_token(PONTO_VIRG);
      break;
      }
    case SE:
    case MARCA_SE:{
      c = If();
      break;
      }
    case ENQUANTO:{
      c = While();
      break;
      }
    case FAZ:{
      c = RepeatUntil();
      break;
      }
    case PARA:{
      c = For();
      break;
      }
    case RETORNO:{
      c = Ret();
      jj_consume_token(PONTO_VIRG);
      break;
      }
    case DELIMITADOR_ESQ:{
      c = Bloco();
      break;
      }
    case PONTO_VIRG:{
      jj_consume_token(PONTO_VIRG);
c = new ASTNode("Comando Vazio (viraDose)");
      break;
      }
    default:
      jj_la1[2] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
{if ("" != null) return c;}
    throw new Error("Missing return statement in function");
}

/* =========================================================
 * DECLARAÇÕES
 * ========================================================= */

/* Declara variável tipada ou variável genérica garrafa. */
  static final public ASTNode Decl() throws ParseException {ASTNode typeNode = null;
  Token tVar = null;
  ASTNode listDecl;
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case TIPO_INT:
    case TIPO_FLOAT:
    case TIPO_BOOL:
    case TIPO_STRING:{
      typeNode = Tipo();
      break;
      }
    case TIPO_VAR:{
      tVar = jj_consume_token(TIPO_VAR);
      break;
      }
    default:
      jj_la1[3] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    listDecl = ListaDecl();
ASTNode node = new ASTNode("Declara\u00e7\u00e3o");
    ASTNode typeDetail = (typeNode != null) ? typeNode : new ASTNode("Tipo: garrafa (var)");
    node.addChild(typeDetail);
    node.addChild(listDecl);
    {if ("" != null) return node;}
    throw new Error("Missing return statement in function");
}

/* Lista de itens declarados separados por maisUmaDose. */
  static final public ASTNode ListaDecl() throws ParseException {ASTNode item;
  ASTNode node;
node = new ASTNode("Lista Itens");
    item = ItemDecl();
node.addChild(item);
    label_3:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case VIRGULA:{
        ;
        break;
        }
      default:
        jj_la1[4] = jj_gen;
        break label_3;
      }
      jj_consume_token(VIRGULA);
      item = ItemDecl();
node.addChild(item);
    }
{if ("" != null) return node;}
    throw new Error("Missing return statement in function");
}

/* Item declarado: apenas nome ou nome com valor inicial. */
  static final public ASTNode ItemDecl() throws ParseException {Token tId;
  ASTNode initVal = null;
    tId = jj_consume_token(ID);
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case ATRIBUICAO:{
      jj_consume_token(ATRIBUICAO);
      initVal = Expr();
      break;
      }
    default:
      jj_la1[5] = jj_gen;
      ;
    }
ASTNode node = new ASTNode("Vari\u00e1vel: " + tId.image);
    if (initVal != null) {
      ASTNode attr = new ASTNode("Atribui\u00e7\u00e3o Inicial (engarrafar)");
      attr.addChild(initVal);
      node.addChild(attr);
    }
    {if ("" != null) return node;}
    throw new Error("Missing return statement in function");
}

/* Tipos primitivos da linguagem. */
  static final public ASTNode Tipo() throws ParseException {Token t = null;
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case TIPO_INT:{
      t = jj_consume_token(TIPO_INT);
      break;
      }
    case TIPO_FLOAT:{
      t = jj_consume_token(TIPO_FLOAT);
      break;
      }
    case TIPO_BOOL:{
      t = jj_consume_token(TIPO_BOOL);
      break;
      }
    case TIPO_STRING:{
      t = jj_consume_token(TIPO_STRING);
      break;
      }
    default:
      jj_la1[6] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
{if ("" != null) return new ASTNode("Tipo: " + t.image);}
    throw new Error("Missing return statement in function");
}

/* =========================================================
 * COMANDOS INICIADOS POR ID
 * ========================================================= */

/* Um comando que começa com identificador. */
  static final public ASTNode StmtFromId() throws ParseException {Token tId;
  ASTNode suffix;
    tId = jj_consume_token(ID);
    suffix = StmtIdSuffix(tId.image);
{if ("" != null) return suffix;}
    throw new Error("Missing return statement in function");
}

/* Depois do ID, decide se é atribuição ou chamada de função. */
  static final public ASTNode StmtIdSuffix(String idName) throws ParseException {ASTNode expr;
  ASTNode args;
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case ATRIBUICAO:{
      jj_consume_token(ATRIBUICAO);
      expr = Expr();
ASTNode node = new ASTNode("Atribui\u00e7\u00e3o (engarrafar) para: " + idName);
        node.addChild(expr);
        {if ("" != null) return node;}
      break;
      }
    case ABRE_PAR:{
      jj_consume_token(ABRE_PAR);
      args = ArgsOpt();
      jj_consume_token(FECHA_PAR);
ASTNode node = new ASTNode("Chamada de Fun\u00e7\u00e3o: " + idName);
        node.addChild(args);
        {if ("" != null) return node;}
      break;
      }
    default:
      jj_la1[7] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
}

/* =========================================================
 * ENTRADA E SAÍDA
 * ========================================================= */

/* Comando de impressão ou leitura. */
  static final public ASTNode Io() throws ParseException {ASTNode list;
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case IMPRIME:{
      jj_consume_token(IMPRIME);
      jj_consume_token(ABRE_PAR);
      list = PrintList();
      jj_consume_token(FECHA_PAR);
ASTNode node = new ASTNode("Impress\u00e3o (serveNoCopo)");
        node.addChild(list);
        {if ("" != null) return node;}
      break;
      }
    case ENTRADA:{
      jj_consume_token(ENTRADA);
      jj_consume_token(ABRE_PAR);
      list = ReadList();
      jj_consume_token(FECHA_PAR);
ASTNode node = new ASTNode("Leitura (pedeNoBalcao)");
        node.addChild(list);
        {if ("" != null) return node;}
      break;
      }
    default:
      jj_la1[8] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
}

/* Lista de expressões para impressão. */
  static final public ASTNode PrintList() throws ParseException {ASTNode expr;
  ASTNode node;
node = new ASTNode("Lista de Express\u00f5es");
    expr = Expr();
node.addChild(expr);
    label_4:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case VIRGULA:{
        ;
        break;
        }
      default:
        jj_la1[9] = jj_gen;
        break label_4;
      }
      jj_consume_token(VIRGULA);
      expr = Expr();
node.addChild(expr);
    }
{if ("" != null) return node;}
    throw new Error("Missing return statement in function");
}

/* Lista de identificadores para leitura. */
  static final public ASTNode ReadList() throws ParseException {Token tId;
  ASTNode node;
node = new ASTNode("Lista de Destinos");
    tId = jj_consume_token(ID);
node.addChild(new ASTNode("Vari\u00e1vel: " + tId.image));
    label_5:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case VIRGULA:{
        ;
        break;
        }
      default:
        jj_la1[10] = jj_gen;
        break label_5;
      }
      jj_consume_token(VIRGULA);
      tId = jj_consume_token(ID);
node.addChild(new ASTNode("Vari\u00e1vel: " + tId.image));
    }
{if ("" != null) return node;}
    throw new Error("Missing return statement in function");
}

/* =========================================================
 * CONDICIONAL
 * ========================================================= */

/* Condicional com marcador opcional mestreAlambique. */
  static final public ASTNode If() throws ParseException {boolean hasMarca = false;
  ASTNode cond;
  ASTNode thenBloc;
  ASTNode elseBloc = null;
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case MARCA_SE:{
      jj_consume_token(MARCA_SE);
hasMarca = true;
      break;
      }
    default:
      jj_la1[11] = jj_gen;
      ;
    }
    jj_consume_token(SE);
    jj_consume_token(ABRE_PAR);
    cond = Expr();
    jj_consume_token(FECHA_PAR);
    thenBloc = Bloco();
    elseBloc = ElseOpt();
String label = "Condicional (seDerBoa)";
    if (hasMarca) {
      label += " [mestreAlambique]";
    }
    ASTNode node = new ASTNode(label);
    node.addChild(cond);
    node.addChild(thenBloc);
    if (elseBloc != null) {
      node.addChild(elseBloc);
    }
    {if ("" != null) return node;}
    throw new Error("Missing return statement in function");
}

/* Else opcional. */
  static final public ASTNode ElseOpt() throws ParseException {ASTNode elseBloc = null;
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case SENAO:{
      jj_consume_token(SENAO);
      elseBloc = Bloco();
      break;
      }
    default:
      jj_la1[12] = jj_gen;
      ;
    }
if (elseBloc != null) {
      ASTNode node = new ASTNode("Sen\u00e3o (seDerRuim)");
      node.addChild(elseBloc);
      {if ("" != null) return node;}
    }
    {if ("" != null) return null;}
    throw new Error("Missing return statement in function");
}

/* =========================================================
 * LAÇOS
 * ========================================================= */

/* Laço while. */
  static final public ASTNode While() throws ParseException {ASTNode cond;
  ASTNode body;
    jj_consume_token(ENQUANTO);
    jj_consume_token(ABRE_PAR);
    cond = Expr();
    jj_consume_token(FECHA_PAR);
    body = Bloco();
ASTNode node = new ASTNode("La\u00e7o Enquanto (enquantoTemCana)");
    node.addChild(cond);
    node.addChild(body);
    {if ("" != null) return node;}
    throw new Error("Missing return statement in function");
}

/* Laço repeat-until. */
  static final public ASTNode RepeatUntil() throws ParseException {ASTNode body;
  ASTNode cond;
    jj_consume_token(FAZ);
    body = Bloco();
    jj_consume_token(ATE);
    jj_consume_token(ABRE_PAR);
    cond = Expr();
    jj_consume_token(FECHA_PAR);
    jj_consume_token(PONTO_VIRG);
ASTNode node = new ASTNode("Repita (tomaUma ... ateFicarTonto)");
    node.addChild(body);
    node.addChild(cond);
    {if ("" != null) return node;}
    throw new Error("Missing return statement in function");
}

/* Laço for. */
  static final public ASTNode For() throws ParseException {ASTNode init = null;
  ASTNode cond = null;
  ASTNode post = null;
  ASTNode body;
    jj_consume_token(PARA);
    jj_consume_token(ABRE_PAR);
    init = ForInitOpt();
    jj_consume_token(PONTO_VIRG);
    cond = ExprOpt();
    jj_consume_token(PONTO_VIRG);
    post = ForPostOpt();
    jj_consume_token(FECHA_PAR);
    body = Bloco();
ASTNode node = new ASTNode("La\u00e7o Para (rodada)");
    node.addChild(init != null ? init : new ASTNode("Inicializa\u00e7\u00e3o: Vazia"));
    node.addChild(cond != null ? cond : new ASTNode("Condi\u00e7\u00e3o: Vazia"));
    node.addChild(post != null ? post : new ASTNode("P\u00f3s-execu\u00e7\u00e3o: Vazia"));
    node.addChild(body);
    {if ("" != null) return node;}
    throw new Error("Missing return statement in function");
}

/* Inicialização opcional do for. */
  static final public ASTNode ForInitOpt() throws ParseException {ASTNode typeNode = null;
  Token tVar = null;
  ASTNode listDecl = null;
  ASTNode stmt = null;
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case TIPO_INT:
    case TIPO_FLOAT:
    case TIPO_BOOL:
    case TIPO_STRING:
    case TIPO_VAR:
    case ID:{
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case TIPO_INT:
      case TIPO_FLOAT:
      case TIPO_BOOL:
      case TIPO_STRING:
      case TIPO_VAR:{
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case TIPO_INT:
        case TIPO_FLOAT:
        case TIPO_BOOL:
        case TIPO_STRING:{
          typeNode = Tipo();
          break;
          }
        case TIPO_VAR:{
          tVar = jj_consume_token(TIPO_VAR);
          break;
          }
        default:
          jj_la1[13] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
        listDecl = ListaDecl();
ASTNode node = new ASTNode("Inicializa\u00e7\u00e3o (Declara\u00e7\u00e3o)");
          ASTNode typeDetail = (typeNode != null) ? typeNode : new ASTNode("Tipo: garrafa (var)");
          node.addChild(typeDetail);
          node.addChild(listDecl);
          {if ("" != null) return node;}
        break;
        }
      case ID:{
        stmt = IdStmtCab();
{if ("" != null) return stmt;}
        break;
        }
      default:
        jj_la1[14] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      break;
      }
    default:
      jj_la1[15] = jj_gen;
      ;
    }
{if ("" != null) return null;}
    throw new Error("Missing return statement in function");
}

/* Condição opcional do for. */
  static final public ASTNode ExprOpt() throws ParseException {ASTNode e = null;
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case ABRE_PAR:
    case TRUE:
    case FALSE:
    case SUBTRACAO:
    case NEGACAO:
    case NUMERO_FLOAT:
    case NUMERO_INT:
    case STR:
    case ID:{
      e = Expr();
      break;
      }
    default:
      jj_la1[16] = jj_gen;
      ;
    }
{if ("" != null) return e;}
    throw new Error("Missing return statement in function");
}

/* Pós-execução opcional do for. */
  static final public ASTNode ForPostOpt() throws ParseException {ASTNode stmt = null;
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case ID:{
      stmt = IdStmtCab();
      break;
      }
    default:
      jj_la1[17] = jj_gen;
      ;
    }
{if ("" != null) return stmt;}
    throw new Error("Missing return statement in function");
}

/* Atribuição ou chamada de função dentro do cabeçalho do for. */
  static final public ASTNode IdStmtCab() throws ParseException {Token tId;
  ASTNode suffix;
    tId = jj_consume_token(ID);
    suffix = StmtIdSuffix(tId.image);
{if ("" != null) return suffix;}
    throw new Error("Missing return statement in function");
}

/* =========================================================
 * FUNÇÕES E RETORNO
 * ========================================================= */

/* Declaração de função. */
  static final public ASTNode DeclFun() throws ParseException {Token tName;
  ASTNode retType;
  ASTNode params;
  ASTNode body;
    jj_consume_token(FUNCAO);
    retType = RetTipo();
    tName = jj_consume_token(ID);
    jj_consume_token(ABRE_PAR);
    params = ParamsOpt();
    jj_consume_token(FECHA_PAR);
    body = Bloco();
ASTNode node = new ASTNode("Fun\u00e7\u00e3o (alambique): " + tName.image);
    node.addChild(retType);
    node.addChild(params);
    node.addChild(body);
    {if ("" != null) return node;}
    throw new Error("Missing return statement in function");
}

/* Tipo de retorno: tipo primitivo ou semDose. */
  static final public ASTNode RetTipo() throws ParseException {ASTNode typeNode = null;
  Token tVoid = null;
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case TIPO_INT:
    case TIPO_FLOAT:
    case TIPO_BOOL:
    case TIPO_STRING:{
      typeNode = Tipo();
      break;
      }
    case VOID:{
      tVoid = jj_consume_token(VOID);
      break;
      }
    default:
      jj_la1[18] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
if (typeNode != null) {if ("" != null) return typeNode;}
    {if ("" != null) return new ASTNode("Tipo Retorno: semDose (void)");}
    throw new Error("Missing return statement in function");
}

/* Parâmetros opcionais. */
  static final public ASTNode ParamsOpt() throws ParseException {ASTNode params = null;
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case TIPO_INT:
    case TIPO_FLOAT:
    case TIPO_BOOL:
    case TIPO_STRING:{
      params = Params();
      break;
      }
    default:
      jj_la1[19] = jj_gen;
      ;
    }
if (params != null) {if ("" != null) return params;}
    {if ("" != null) return new ASTNode("Par\u00e2metros: Nenhum");}
    throw new Error("Missing return statement in function");
}

/* Lista de parâmetros separados por maisUmaDose. */
  static final public ASTNode Params() throws ParseException {ASTNode p;
  ASTNode node;
node = new ASTNode("Par\u00e2metros");
    p = Param();
node.addChild(p);
    label_6:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case VIRGULA:{
        ;
        break;
        }
      default:
        jj_la1[20] = jj_gen;
        break label_6;
      }
      jj_consume_token(VIRGULA);
      p = Param();
node.addChild(p);
    }
{if ("" != null) return node;}
    throw new Error("Missing return statement in function");
}

/* Um parâmetro possui tipo e nome. */
  static final public ASTNode Param() throws ParseException {ASTNode type;
  Token tId;
    type = Tipo();
    tId = jj_consume_token(ID);
ASTNode node = new ASTNode("Par\u00e2metro: " + tId.image);
    node.addChild(type);
    {if ("" != null) return node;}
    throw new Error("Missing return statement in function");
}

/* Retorno sem expressão ou com expressão. */
  static final public ASTNode Ret() throws ParseException {ASTNode val = null;
    jj_consume_token(RETORNO);
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case ABRE_PAR:
    case TRUE:
    case FALSE:
    case SUBTRACAO:
    case NEGACAO:
    case NUMERO_FLOAT:
    case NUMERO_INT:
    case STR:
    case ID:{
      val = Expr();
      break;
      }
    default:
      jj_la1[21] = jj_gen;
      ;
    }
ASTNode node = new ASTNode("Retorno (devolveDose)");
    if (val != null) {
      node.addChild(val);
    }
    {if ("" != null) return node;}
    throw new Error("Missing return statement in function");
}

/* =========================================================
 * ARGUMENTOS DE FUNÇÃO
 * ========================================================= */

/* Lista opcional de argumentos. */
  static final public ASTNode ArgsOpt() throws ParseException {ASTNode expr;
  ASTNode node;
node = new ASTNode("Argumentos");
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case ABRE_PAR:
    case TRUE:
    case FALSE:
    case SUBTRACAO:
    case NEGACAO:
    case NUMERO_FLOAT:
    case NUMERO_INT:
    case STR:
    case ID:{
      expr = Expr();
node.addChild(expr);
      label_7:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case VIRGULA:{
          ;
          break;
          }
        default:
          jj_la1[22] = jj_gen;
          break label_7;
        }
        jj_consume_token(VIRGULA);
        expr = Expr();
node.addChild(expr);
      }
      break;
      }
    default:
      jj_la1[23] = jj_gen;
      ;
    }
{if ("" != null) return node;}
    throw new Error("Missing return statement in function");
}

/* =========================================================
 * EXPRESSÕES
 * A ordem abaixo implementa a precedência dos operadores:
 * ||, &&, igualdade, relacionais, soma/subtração,
 * multiplicação/divisão, unários e primários.
 * ========================================================= */
  static final public 
ASTNode Expr() throws ParseException {ASTNode node;
    node = ExprOr();
{if ("" != null) return node;}
    throw new Error("Missing return statement in function");
}

  static final public ASTNode ExprOr() throws ParseException {ASTNode left;
  ASTNode right;
  Token tOp;
    left = ExprAnd();
    label_8:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case OU_LOGICO:{
        ;
        break;
        }
      default:
        jj_la1[24] = jj_gen;
        break label_8;
      }
      tOp = jj_consume_token(OU_LOGICO);
      right = ExprAnd();
ASTNode opNode = new ASTNode("Opera\u00e7\u00e3o L\u00f3gica: " + tOp.image);
      opNode.addChild(left);
      opNode.addChild(right);
      left = opNode;
    }
{if ("" != null) return left;}
    throw new Error("Missing return statement in function");
}

  static final public ASTNode ExprAnd() throws ParseException {ASTNode left;
  ASTNode right;
  Token tOp;
    left = ExprEq();
    label_9:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case E_LOGICO:{
        ;
        break;
        }
      default:
        jj_la1[25] = jj_gen;
        break label_9;
      }
      tOp = jj_consume_token(E_LOGICO);
      right = ExprEq();
ASTNode opNode = new ASTNode("Opera\u00e7\u00e3o L\u00f3gica: " + tOp.image);
      opNode.addChild(left);
      opNode.addChild(right);
      left = opNode;
    }
{if ("" != null) return left;}
    throw new Error("Missing return statement in function");
}

  static final public ASTNode ExprEq() throws ParseException {ASTNode left;
  ASTNode right;
  Token tOp;
    left = ExprRel();
    label_10:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case IGUALDADE:
      case DIFERENTE:{
        ;
        break;
        }
      default:
        jj_la1[26] = jj_gen;
        break label_10;
      }
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case IGUALDADE:{
        tOp = jj_consume_token(IGUALDADE);
        break;
        }
      case DIFERENTE:{
        tOp = jj_consume_token(DIFERENTE);
        break;
        }
      default:
        jj_la1[27] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      right = ExprRel();
ASTNode opNode = new ASTNode("Compara\u00e7\u00e3o: " + tOp.image);
      opNode.addChild(left);
      opNode.addChild(right);
      left = opNode;
    }
{if ("" != null) return left;}
    throw new Error("Missing return statement in function");
}

  static final public ASTNode ExprRel() throws ParseException {ASTNode left;
  ASTNode right;
  Token tOp;
    left = ExprAdd();
    label_11:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case MENOR_IGUAL:
      case MAIOR_IGUAL:
      case MAIOR:
      case MENOR:{
        ;
        break;
        }
      default:
        jj_la1[28] = jj_gen;
        break label_11;
      }
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case MENOR:{
        tOp = jj_consume_token(MENOR);
        break;
        }
      case MAIOR:{
        tOp = jj_consume_token(MAIOR);
        break;
        }
      case MENOR_IGUAL:{
        tOp = jj_consume_token(MENOR_IGUAL);
        break;
        }
      case MAIOR_IGUAL:{
        tOp = jj_consume_token(MAIOR_IGUAL);
        break;
        }
      default:
        jj_la1[29] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      right = ExprAdd();
ASTNode opNode = new ASTNode("Compara\u00e7\u00e3o: " + tOp.image);
      opNode.addChild(left);
      opNode.addChild(right);
      left = opNode;
    }
{if ("" != null) return left;}
    throw new Error("Missing return statement in function");
}

  static final public ASTNode ExprAdd() throws ParseException {ASTNode left;
  ASTNode right;
  Token tOp;
    left = ExprMul();
    label_12:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case SOMA:
      case SUBTRACAO:{
        ;
        break;
        }
      default:
        jj_la1[30] = jj_gen;
        break label_12;
      }
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case SOMA:{
        tOp = jj_consume_token(SOMA);
        break;
        }
      case SUBTRACAO:{
        tOp = jj_consume_token(SUBTRACAO);
        break;
        }
      default:
        jj_la1[31] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      right = ExprMul();
ASTNode opNode = new ASTNode("Opera\u00e7\u00e3o Aritm\u00e9tica: " + tOp.image);
      opNode.addChild(left);
      opNode.addChild(right);
      left = opNode;
    }
{if ("" != null) return left;}
    throw new Error("Missing return statement in function");
}

  static final public ASTNode ExprMul() throws ParseException {ASTNode left;
  ASTNode right;
  Token tOp;
    left = ExprUn();
    label_13:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case MULTIPLICACAO:
      case DIVISAO:{
        ;
        break;
        }
      default:
        jj_la1[32] = jj_gen;
        break label_13;
      }
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case MULTIPLICACAO:{
        tOp = jj_consume_token(MULTIPLICACAO);
        break;
        }
      case DIVISAO:{
        tOp = jj_consume_token(DIVISAO);
        break;
        }
      default:
        jj_la1[33] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      right = ExprUn();
ASTNode opNode = new ASTNode("Opera\u00e7\u00e3o Aritm\u00e9tica: " + tOp.image);
      opNode.addChild(left);
      opNode.addChild(right);
      left = opNode;
    }
{if ("" != null) return left;}
    throw new Error("Missing return statement in function");
}

  static final public ASTNode ExprUn() throws ParseException {ASTNode expr;
  Token tOp = null;
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case NEGACAO:{
      tOp = jj_consume_token(NEGACAO);
      expr = ExprUn();
ASTNode node = new ASTNode("Opera\u00e7\u00e3o Un\u00e1ria: " + tOp.image);
        node.addChild(expr);
        {if ("" != null) return node;}
      break;
      }
    case SUBTRACAO:{
      tOp = jj_consume_token(SUBTRACAO);
      expr = ExprUn();
ASTNode node = new ASTNode("Opera\u00e7\u00e3o Un\u00e1ria: " + tOp.image);
        node.addChild(expr);
        {if ("" != null) return node;}
      break;
      }
    case ABRE_PAR:
    case TRUE:
    case FALSE:
    case NUMERO_FLOAT:
    case NUMERO_INT:
    case STR:
    case ID:{
      expr = Prim();
{if ("" != null) return expr;}
      break;
      }
    default:
      jj_la1[34] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
}

/* Valor primário de uma expressão. */
  static final public ASTNode Prim() throws ParseException {Token t = null;
  ASTNode suffix = null;
  ASTNode expr = null;
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case NUMERO_FLOAT:{
      t = jj_consume_token(NUMERO_FLOAT);
{if ("" != null) return new ASTNode("Literal Real: " + t.image);}
      break;
      }
    case NUMERO_INT:{
      t = jj_consume_token(NUMERO_INT);
{if ("" != null) return new ASTNode("Literal Inteiro: " + t.image);}
      break;
      }
    case TRUE:{
      t = jj_consume_token(TRUE);
{if ("" != null) return new ASTNode("Literal Booleano: " + t.image);}
      break;
      }
    case FALSE:{
      t = jj_consume_token(FALSE);
{if ("" != null) return new ASTNode("Literal Booleano: " + t.image);}
      break;
      }
    case STR:{
      t = jj_consume_token(STR);
{if ("" != null) return new ASTNode("Literal R\u00f3tulo: " + t.image);}
      break;
      }
    case ID:{
      t = jj_consume_token(ID);
      suffix = PrimIdSuffix(t.image);
{if ("" != null) return suffix;}
      break;
      }
    case ABRE_PAR:{
      jj_consume_token(ABRE_PAR);
      expr = Expr();
      jj_consume_token(FECHA_PAR);
ASTNode node = new ASTNode("Express\u00e3o Agrupada");
          node.addChild(expr);
          {if ("" != null) return node;}
      break;
      }
    default:
      jj_la1[35] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
}

/* Depois de um ID dentro de expressão, decide se é variável ou chamada. */
  static final public ASTNode PrimIdSuffix(String idName) throws ParseException {ASTNode args = null;
  boolean isCall = false;
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case ABRE_PAR:{
      jj_consume_token(ABRE_PAR);
      args = ArgsOpt();
      jj_consume_token(FECHA_PAR);
isCall = true;
      break;
      }
    default:
      jj_la1[36] = jj_gen;
      ;
    }
if (isCall) {
      ASTNode node = new ASTNode("Chamada de Fun\u00e7\u00e3o: " + idName);
      node.addChild(args);
      {if ("" != null) return node;}
    } else {
      {if ("" != null) return new ASTNode("Refer\u00eancia de Vari\u00e1vel: " + idName);}
    }
    throw new Error("Missing return statement in function");
}

  static private boolean jj_initialized_once = false;
  /** Generated Token Manager. */
  static public compiladorCachacaScriptTokenManager token_source;
  static SimpleCharStream jj_input_stream;
  /** Current token. */
  static public Token token;
  /** Next token. */
  static public Token jj_nt;
  static private int jj_ntk;
  static private int jj_gen;
  static final private int[] jj_la1 = new int[37];
  static private int[] jj_la1_0;
  static private int[] jj_la1_1;
  static {
	   jj_la1_init_0();
	   jj_la1_init_1();
	}
	private static void jj_la1_init_0() {
	   jj_la1_0 = new int[] {0x2000000,0xf5772200,0xf5772200,0xf0000000,0x8000,0x4000,0xf0000000,0x4800,0x30000,0x8000,0x8000,0x100000,0x80000,0xf0000000,0xf0000000,0xf0000000,0x800,0x0,0xf8000000,0xf0000000,0x8000,0x800,0x8000,0x800,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x800,0x800,0x800,};
	}
	private static void jj_la1_init_1() {
	   jj_la1_1 = new int[] {0x0,0x80001,0x80001,0x1,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x1,0x80001,0x80001,0xf8406,0x80000,0x0,0x0,0x0,0xf8406,0x0,0xf8406,0x100,0x80,0x60,0x60,0x6018,0x6018,0x600,0x600,0x1800,0x1800,0xf8406,0xf0006,0x0,};
	}

  /** Constructor with InputStream. */
  public compiladorCachacaScript(java.io.InputStream stream) {
	  this(stream, null);
  }
  /** Constructor with InputStream and supplied encoding */
  public compiladorCachacaScript(java.io.InputStream stream, String encoding) {
	 if (jj_initialized_once) {
	   System.out.println("ERROR: Second call to constructor of static parser.  ");
	   System.out.println("	   You must either use ReInit() or set the JavaCC option STATIC to false");
	   System.out.println("	   during parser generation.");
	   throw new Error();
	 }
	 jj_initialized_once = true;
	 try { jj_input_stream = new SimpleCharStream(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
	 token_source = new compiladorCachacaScriptTokenManager(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 37; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  static public void ReInit(java.io.InputStream stream) {
	  ReInit(stream, null);
  }
  /** Reinitialise. */
  static public void ReInit(java.io.InputStream stream, String encoding) {
	 try { jj_input_stream.ReInit(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
	 token_source.ReInit(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 37; i++) jj_la1[i] = -1;
  }

  /** Constructor. */
  public compiladorCachacaScript(java.io.Reader stream) {
	 if (jj_initialized_once) {
	   System.out.println("ERROR: Second call to constructor of static parser. ");
	   System.out.println("	   You must either use ReInit() or set the JavaCC option STATIC to false");
	   System.out.println("	   during parser generation.");
	   throw new Error();
	 }
	 jj_initialized_once = true;
	 jj_input_stream = new SimpleCharStream(stream, 1, 1);
	 token_source = new compiladorCachacaScriptTokenManager(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 37; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  static public void ReInit(java.io.Reader stream) {
	if (jj_input_stream == null) {
	   jj_input_stream = new SimpleCharStream(stream, 1, 1);
	} else {
	   jj_input_stream.ReInit(stream, 1, 1);
	}
	if (token_source == null) {
 token_source = new compiladorCachacaScriptTokenManager(jj_input_stream);
	}

	 token_source.ReInit(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 37; i++) jj_la1[i] = -1;
  }

  /** Constructor with generated Token Manager. */
  public compiladorCachacaScript(compiladorCachacaScriptTokenManager tm) {
	 if (jj_initialized_once) {
	   System.out.println("ERROR: Second call to constructor of static parser. ");
	   System.out.println("	   You must either use ReInit() or set the JavaCC option STATIC to false");
	   System.out.println("	   during parser generation.");
	   throw new Error();
	 }
	 jj_initialized_once = true;
	 token_source = tm;
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 37; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(compiladorCachacaScriptTokenManager tm) {
	 token_source = tm;
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 37; i++) jj_la1[i] = -1;
  }

  static private Token jj_consume_token(int kind) throws ParseException {
	 Token oldToken;
	 if ((oldToken = token).next != null) token = token.next;
	 else token = token.next = token_source.getNextToken();
	 jj_ntk = -1;
	 if (token.kind == kind) {
	   jj_gen++;
	   return token;
	 }
	 token = oldToken;
	 jj_kind = kind;
	 throw generateParseException();
  }


/** Get the next Token. */
  static final public Token getNextToken() {
	 if (token.next != null) token = token.next;
	 else token = token.next = token_source.getNextToken();
	 jj_ntk = -1;
	 jj_gen++;
	 return token;
  }

/** Get the specific Token. */
  static final public Token getToken(int index) {
	 Token t = token;
	 for (int i = 0; i < index; i++) {
	   if (t.next != null) t = t.next;
	   else t = t.next = token_source.getNextToken();
	 }
	 return t;
  }

  static private int jj_ntk_f() {
	 if ((jj_nt=token.next) == null)
	   return (jj_ntk = (token.next=token_source.getNextToken()).kind);
	 else
	   return (jj_ntk = jj_nt.kind);
  }

  static private java.util.List<int[]> jj_expentries = new java.util.ArrayList<int[]>();
  static private int[] jj_expentry;
  static private int jj_kind = -1;

  /** Generate ParseException. */
  static public ParseException generateParseException() {
	 jj_expentries.clear();
	 boolean[] la1tokens = new boolean[53];
	 if (jj_kind >= 0) {
	   la1tokens[jj_kind] = true;
	   jj_kind = -1;
	 }
	 for (int i = 0; i < 37; i++) {
	   if (jj_la1[i] == jj_gen) {
		 for (int j = 0; j < 32; j++) {
		   if ((jj_la1_0[i] & (1<<j)) != 0) {
			 la1tokens[j] = true;
		   }
		   if ((jj_la1_1[i] & (1<<j)) != 0) {
			 la1tokens[32+j] = true;
		   }
		 }
	   }
	 }
	 for (int i = 0; i < 53; i++) {
	   if (la1tokens[i]) {
		 jj_expentry = new int[1];
		 jj_expentry[0] = i;
		 jj_expentries.add(jj_expentry);
	   }
	 }
	 int[][] exptokseq = new int[jj_expentries.size()][];
	 for (int i = 0; i < jj_expentries.size(); i++) {
	   exptokseq[i] = jj_expentries.get(i);
	 }
	 return new ParseException(token, exptokseq, tokenImage);
  }

  static private boolean trace_enabled;

/** Trace enabled. */
  static final public boolean trace_enabled() {
	 return trace_enabled;
  }

  /** Enable tracing. */
  static final public void enable_tracing() {
  }

  /** Disable tracing. */
  static final public void disable_tracing() {
  }

}
