/* Generated By:JavaCC: Do not edit this line. compiladorCachacaScriptConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface compiladorCachacaScriptConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int COMENTARIO_LINHA = 5;
  /** RegularExpression Id. */
  int COMENTARIO_BLOCO = 6;
  /** RegularExpression Id. */
  int INICIO_PROGRAMA = 7;
  /** RegularExpression Id. */
  int FIM_PROGRAMA = 8;
  /** RegularExpression Id. */
  int DELIMITADOR_ESQ = 9;
  /** RegularExpression Id. */
  int DELIMITADOR_DIR = 10;
  /** RegularExpression Id. */
  int ABRE_PAR = 11;
  /** RegularExpression Id. */
  int FECHA_PAR = 12;
  /** RegularExpression Id. */
  int PONTO_VIRG = 13;
  /** RegularExpression Id. */
  int ATRIBUICAO = 14;
  /** RegularExpression Id. */
  int VIRGULA = 15;
  /** RegularExpression Id. */
  int IMPRIME = 16;
  /** RegularExpression Id. */
  int ENTRADA = 17;
  /** RegularExpression Id. */
  int SE = 18;
  /** RegularExpression Id. */
  int SENAO = 19;
  /** RegularExpression Id. */
  int MARCA_SE = 20;
  /** RegularExpression Id. */
  int ENQUANTO = 21;
  /** RegularExpression Id. */
  int FAZ = 22;
  /** RegularExpression Id. */
  int ATE = 23;
  /** RegularExpression Id. */
  int PARA = 24;
  /** RegularExpression Id. */
  int FUNCAO = 25;
  /** RegularExpression Id. */
  int RETORNO = 26;
  /** RegularExpression Id. */
  int VOID = 27;
  /** RegularExpression Id. */
  int TIPO_INT = 28;
  /** RegularExpression Id. */
  int TIPO_FLOAT = 29;
  /** RegularExpression Id. */
  int TIPO_BOOL = 30;
  /** RegularExpression Id. */
  int TIPO_STRING = 31;
  /** RegularExpression Id. */
  int TIPO_VAR = 32;
  /** RegularExpression Id. */
  int TRUE = 33;
  /** RegularExpression Id. */
  int FALSE = 34;
  /** RegularExpression Id. */
  int MENOR_IGUAL = 35;
  /** RegularExpression Id. */
  int MAIOR_IGUAL = 36;
  /** RegularExpression Id. */
  int IGUALDADE = 37;
  /** RegularExpression Id. */
  int DIFERENTE = 38;
  /** RegularExpression Id. */
  int E_LOGICO = 39;
  /** RegularExpression Id. */
  int OU_LOGICO = 40;
  /** RegularExpression Id. */
  int SOMA = 41;
  /** RegularExpression Id. */
  int SUBTRACAO = 42;
  /** RegularExpression Id. */
  int MULTIPLICACAO = 43;
  /** RegularExpression Id. */
  int DIVISAO = 44;
  /** RegularExpression Id. */
  int MAIOR = 45;
  /** RegularExpression Id. */
  int MENOR = 46;
  /** RegularExpression Id. */
  int NEGACAO = 47;
  /** RegularExpression Id. */
  int NUMERO_FLOAT = 48;
  /** RegularExpression Id. */
  int NUMERO_INT = 49;
  /** RegularExpression Id. */
  int STR = 50;
  /** RegularExpression Id. */
  int ID = 51;
  /** RegularExpression Id. */
  int DIGITO = 52;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "<COMENTARIO_LINHA>",
    "<COMENTARIO_BLOCO>",
    "\"abreAButelada\"",
    "\"fechaAButelada\"",
    "\"abreBarril\"",
    "\"fechaBarril\"",
    "\"abreCopo\"",
    "\"fechaCopo\"",
    "\"viraDose\"",
    "\"engarrafar\"",
    "\"maisUmaDose\"",
    "\"serveNoCopo\"",
    "\"pedeNoBalcao\"",
    "\"seDerBoa\"",
    "\"seDerRuim\"",
    "\"mestreAlambique\"",
    "\"enquantoTemCana\"",
    "\"tomaUma\"",
    "\"ateFicarTonto\"",
    "\"rodada\"",
    "\"alambique\"",
    "\"devolveDose\"",
    "\"semDose\"",
    "\"doseInteira\"",
    "\"doseQuebrada\"",
    "\"taNoGrau\"",
    "\"rotulo\"",
    "\"garrafa\"",
    "\"simPatrao\"",
    "\"nemAPau\"",
    "\"<=\"",
    "\">=\"",
    "\"==\"",
    "\"!=\"",
    "\"&&\"",
    "\"||\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\">\"",
    "\"<\"",
    "\"!\"",
    "<NUMERO_FLOAT>",
    "<NUMERO_INT>",
    "<STR>",
    "<ID>",
    "<DIGITO>",
  };

}
