/* compiladorCachacaScriptTokenManager.java */
/* Generated By:JavaCC: Do not edit this line. compiladorCachacaScriptTokenManager.java */

/** Token Manager. */
public class compiladorCachacaScriptTokenManager implements compiladorCachacaScriptConstants {

  /** Debug output. */
  public static  java.io.PrintStream debugStream = System.out;
  /** Set debug output. */
  public static  void setDebugStream(java.io.PrintStream ds) { debugStream = ds; }
private static final int jjStopStringLiteralDfa_0(int pos, long active0){
   switch (pos)
   {
      case 0:
         if ((active0 & 0x100000000000L) != 0L)
            return 8;
         if ((active0 & 0x7ffffff80L) != 0L)
         {
            jjmatchedKind = 51;
            return 6;
         }
         return -1;
      case 1:
         if ((active0 & 0x7ffffff80L) != 0L)
         {
            jjmatchedKind = 51;
            jjmatchedPos = 1;
            return 6;
         }
         return -1;
      case 2:
         if ((active0 & 0x7ffffff80L) != 0L)
         {
            jjmatchedKind = 51;
            jjmatchedPos = 2;
            return 6;
         }
         return -1;
      case 3:
         if ((active0 & 0x7ffffff80L) != 0L)
         {
            jjmatchedKind = 51;
            jjmatchedPos = 3;
            return 6;
         }
         return -1;
      case 4:
         if ((active0 & 0x7ffffff80L) != 0L)
         {
            jjmatchedKind = 51;
            jjmatchedPos = 4;
            return 6;
         }
         return -1;
      case 5:
         if ((active0 & 0x81000000L) != 0L)
            return 6;
         if ((active0 & 0x77effff80L) != 0L)
         {
            jjmatchedKind = 51;
            jjmatchedPos = 5;
            return 6;
         }
         return -1;
      case 6:
         if ((active0 & 0x508400000L) != 0L)
            return 6;
         if ((active0 & 0x276bfff80L) != 0L)
         {
            jjmatchedKind = 51;
            jjmatchedPos = 6;
            return 6;
         }
         return -1;
      case 7:
         if ((active0 & 0x40042800L) != 0L)
            return 6;
         if ((active0 & 0x236bbd780L) != 0L)
         {
            jjmatchedKind = 51;
            jjmatchedPos = 7;
            return 6;
         }
         return -1;
      case 8:
         if ((active0 & 0x202081000L) != 0L)
            return 6;
         if ((active0 & 0x34b3c780L) != 0L)
         {
            jjmatchedKind = 51;
            jjmatchedPos = 8;
            return 6;
         }
         return -1;
      case 9:
         if ((active0 & 0x34b38580L) != 0L)
         {
            jjmatchedKind = 51;
            jjmatchedPos = 9;
            return 6;
         }
         if ((active0 & 0x4200L) != 0L)
            return 6;
         return -1;
      case 10:
         if ((active0 & 0x14018400L) != 0L)
            return 6;
         if ((active0 & 0x20b20180L) != 0L)
         {
            jjmatchedKind = 51;
            jjmatchedPos = 10;
            return 6;
         }
         return -1;
      case 11:
         if ((active0 & 0x20020000L) != 0L)
            return 6;
         if ((active0 & 0xb00180L) != 0L)
         {
            jjmatchedKind = 51;
            jjmatchedPos = 11;
            return 6;
         }
         return -1;
      case 12:
         if ((active0 & 0x300100L) != 0L)
         {
            jjmatchedKind = 51;
            jjmatchedPos = 12;
            return 6;
         }
         if ((active0 & 0x800080L) != 0L)
            return 6;
         return -1;
      case 13:
         if ((active0 & 0x300000L) != 0L)
         {
            jjmatchedKind = 51;
            jjmatchedPos = 13;
            return 6;
         }
         if ((active0 & 0x100L) != 0L)
            return 6;
         return -1;
      default :
         return -1;
   }
}
private static final int jjStartNfa_0(int pos, long active0){
   return jjMoveNfa_0(jjStopStringLiteralDfa_0(pos, active0), pos + 1);
}
static private int jjStopAtPos(int pos, int kind)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   return pos + 1;
}
static private int jjMoveStringLiteralDfa0_0(){
   switch(curChar)
   {
      case 33:
         jjmatchedKind = 47;
         return jjMoveStringLiteralDfa1_0(0x4000000000L);
      case 38:
         return jjMoveStringLiteralDfa1_0(0x8000000000L);
      case 42:
         return jjStopAtPos(0, 43);
      case 43:
         return jjStopAtPos(0, 41);
      case 45:
         return jjStopAtPos(0, 42);
      case 47:
         return jjStartNfaWithStates_0(0, 44, 8);
      case 60:
         jjmatchedKind = 46;
         return jjMoveStringLiteralDfa1_0(0x800000000L);
      case 61:
         return jjMoveStringLiteralDfa1_0(0x2000000000L);
      case 62:
         jjmatchedKind = 45;
         return jjMoveStringLiteralDfa1_0(0x1000000000L);
      case 97:
         return jjMoveStringLiteralDfa1_0(0x2800a80L);
      case 100:
         return jjMoveStringLiteralDfa1_0(0x34000000L);
      case 101:
         return jjMoveStringLiteralDfa1_0(0x204000L);
      case 102:
         return jjMoveStringLiteralDfa1_0(0x1500L);
      case 103:
         return jjMoveStringLiteralDfa1_0(0x100000000L);
      case 109:
         return jjMoveStringLiteralDfa1_0(0x108000L);
      case 110:
         return jjMoveStringLiteralDfa1_0(0x400000000L);
      case 112:
         return jjMoveStringLiteralDfa1_0(0x20000L);
      case 114:
         return jjMoveStringLiteralDfa1_0(0x81000000L);
      case 115:
         return jjMoveStringLiteralDfa1_0(0x2080d0000L);
      case 116:
         return jjMoveStringLiteralDfa1_0(0x40400000L);
      case 118:
         return jjMoveStringLiteralDfa1_0(0x2000L);
      case 124:
         return jjMoveStringLiteralDfa1_0(0x10000000000L);
      default :
         return jjMoveNfa_0(0, 0);
   }
}
static private int jjMoveStringLiteralDfa1_0(long active0){
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(0, active0);
      return 1;
   }
   switch(curChar)
   {
      case 38:
         if ((active0 & 0x8000000000L) != 0L)
            return jjStopAtPos(1, 39);
         break;
      case 61:
         if ((active0 & 0x800000000L) != 0L)
            return jjStopAtPos(1, 35);
         else if ((active0 & 0x1000000000L) != 0L)
            return jjStopAtPos(1, 36);
         else if ((active0 & 0x2000000000L) != 0L)
            return jjStopAtPos(1, 37);
         else if ((active0 & 0x4000000000L) != 0L)
            return jjStopAtPos(1, 38);
         break;
      case 97:
         return jjMoveStringLiteralDfa2_0(active0, 0x140008000L);
      case 98:
         return jjMoveStringLiteralDfa2_0(active0, 0xa80L);
      case 101:
         return jjMoveStringLiteralDfa2_0(active0, 0x40c1f1500L);
      case 105:
         return jjMoveStringLiteralDfa2_0(active0, 0x200002000L);
      case 108:
         return jjMoveStringLiteralDfa2_0(active0, 0x2000000L);
      case 110:
         return jjMoveStringLiteralDfa2_0(active0, 0x204000L);
      case 111:
         return jjMoveStringLiteralDfa2_0(active0, 0xb1400000L);
      case 116:
         return jjMoveStringLiteralDfa2_0(active0, 0x800000L);
      case 124:
         if ((active0 & 0x10000000000L) != 0L)
            return jjStopAtPos(1, 40);
         break;
      default :
         break;
   }
   return jjStartNfa_0(0, active0);
}
static private int jjMoveStringLiteralDfa2_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(0, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(1, active0);
      return 2;
   }
   switch(curChar)
   {
      case 68:
         return jjMoveStringLiteralDfa3_0(active0, 0xc0000L);
      case 78:
         return jjMoveStringLiteralDfa3_0(active0, 0x40000000L);
      case 97:
         return jjMoveStringLiteralDfa3_0(active0, 0x2000000L);
      case 99:
         return jjMoveStringLiteralDfa3_0(active0, 0x1500L);
      case 100:
         return jjMoveStringLiteralDfa3_0(active0, 0x1020000L);
      case 101:
         return jjMoveStringLiteralDfa3_0(active0, 0x800000L);
      case 103:
         return jjMoveStringLiteralDfa3_0(active0, 0x4000L);
      case 105:
         return jjMoveStringLiteralDfa3_0(active0, 0x8000L);
      case 109:
         return jjMoveStringLiteralDfa3_0(active0, 0x608400000L);
      case 113:
         return jjMoveStringLiteralDfa3_0(active0, 0x200000L);
      case 114:
         return jjMoveStringLiteralDfa3_0(active0, 0x100012a80L);
      case 115:
         return jjMoveStringLiteralDfa3_0(active0, 0x30100000L);
      case 116:
         return jjMoveStringLiteralDfa3_0(active0, 0x80000000L);
      case 118:
         return jjMoveStringLiteralDfa3_0(active0, 0x4000000L);
      default :
         break;
   }
   return jjStartNfa_0(1, active0);
}
static private int jjMoveStringLiteralDfa3_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(1, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(2, active0);
      return 3;
   }
   switch(curChar)
   {
      case 65:
         return jjMoveStringLiteralDfa4_0(active0, 0x400000000L);
      case 68:
         return jjMoveStringLiteralDfa4_0(active0, 0x8000000L);
      case 70:
         return jjMoveStringLiteralDfa4_0(active0, 0x800000L);
      case 80:
         return jjMoveStringLiteralDfa4_0(active0, 0x200000000L);
      case 97:
         return jjMoveStringLiteralDfa4_0(active0, 0x1406000L);
      case 101:
         return jjMoveStringLiteralDfa4_0(active0, 0x300e0a80L);
      case 104:
         return jjMoveStringLiteralDfa4_0(active0, 0x1500L);
      case 109:
         return jjMoveStringLiteralDfa4_0(active0, 0x2000000L);
      case 111:
         return jjMoveStringLiteralDfa4_0(active0, 0x44000000L);
      case 114:
         return jjMoveStringLiteralDfa4_0(active0, 0x100000000L);
      case 115:
         return jjMoveStringLiteralDfa4_0(active0, 0x8000L);
      case 116:
         return jjMoveStringLiteralDfa4_0(active0, 0x100000L);
      case 117:
         return jjMoveStringLiteralDfa4_0(active0, 0x80200000L);
      case 118:
         return jjMoveStringLiteralDfa4_0(active0, 0x10000L);
      default :
         break;
   }
   return jjStartNfa_0(2, active0);
}
static private int jjMoveStringLiteralDfa4_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(2, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(3, active0);
      return 4;
   }
   switch(curChar)
   {
      case 65:
         return jjMoveStringLiteralDfa5_0(active0, 0x80L);
      case 66:
         return jjMoveStringLiteralDfa5_0(active0, 0x200L);
      case 67:
         return jjMoveStringLiteralDfa5_0(active0, 0x800L);
      case 68:
         return jjMoveStringLiteralDfa5_0(active0, 0x2000L);
      case 71:
         return jjMoveStringLiteralDfa5_0(active0, 0x40000000L);
      case 73:
         return jjMoveStringLiteralDfa5_0(active0, 0x10000000L);
      case 78:
         return jjMoveStringLiteralDfa5_0(active0, 0x20000L);
      case 80:
         return jjMoveStringLiteralDfa5_0(active0, 0x400000000L);
      case 81:
         return jjMoveStringLiteralDfa5_0(active0, 0x20000000L);
      case 85:
         return jjMoveStringLiteralDfa5_0(active0, 0x408000L);
      case 97:
         return jjMoveStringLiteralDfa5_0(active0, 0x300201500L);
      case 98:
         return jjMoveStringLiteralDfa5_0(active0, 0x2000000L);
      case 100:
         return jjMoveStringLiteralDfa5_0(active0, 0x1000000L);
      case 101:
         return jjMoveStringLiteralDfa5_0(active0, 0x10000L);
      case 105:
         return jjMoveStringLiteralDfa5_0(active0, 0x800000L);
      case 108:
         return jjMoveStringLiteralDfa5_0(active0, 0x84000000L);
      case 111:
         return jjMoveStringLiteralDfa5_0(active0, 0x8000000L);
      case 114:
         return jjMoveStringLiteralDfa5_0(active0, 0x1c4000L);
      default :
         break;
   }
   return jjStartNfa_0(3, active0);
}
static private int jjMoveStringLiteralDfa5_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(3, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(4, active0);
      return 5;
   }
   switch(curChar)
   {
      case 65:
         return jjMoveStringLiteralDfa6_0(active0, 0x100L);
      case 66:
         return jjMoveStringLiteralDfa6_0(active0, 0x40480L);
      case 67:
         return jjMoveStringLiteralDfa6_0(active0, 0x1000L);
      case 78:
         return jjMoveStringLiteralDfa6_0(active0, 0x10000L);
      case 82:
         return jjMoveStringLiteralDfa6_0(active0, 0x80000L);
      case 97:
         if ((active0 & 0x1000000L) != 0L)
            return jjStartNfaWithStates_0(5, 24, 6);
         return jjMoveStringLiteralDfa6_0(active0, 0x400000200L);
      case 99:
         return jjMoveStringLiteralDfa6_0(active0, 0x800000L);
      case 101:
         return jjMoveStringLiteralDfa6_0(active0, 0x100000L);
      case 102:
         return jjMoveStringLiteralDfa6_0(active0, 0x100000000L);
      case 105:
         return jjMoveStringLiteralDfa6_0(active0, 0x2000000L);
      case 109:
         return jjMoveStringLiteralDfa6_0(active0, 0x408000L);
      case 110:
         return jjMoveStringLiteralDfa6_0(active0, 0x10200000L);
      case 111:
         if ((active0 & 0x80000000L) != 0L)
            return jjStartNfaWithStates_0(5, 31, 6);
         return jjMoveStringLiteralDfa6_0(active0, 0x22800L);
      case 114:
         return jjMoveStringLiteralDfa6_0(active0, 0x40004000L);
      case 115:
         return jjMoveStringLiteralDfa6_0(active0, 0x8000000L);
      case 116:
         return jjMoveStringLiteralDfa6_0(active0, 0x200000000L);
      case 117:
         return jjMoveStringLiteralDfa6_0(active0, 0x20000000L);
      case 118:
         return jjMoveStringLiteralDfa6_0(active0, 0x4000000L);
      default :
         break;
   }
   return jjStartNfa_0(4, active0);
}
static private int jjMoveStringLiteralDfa6_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(4, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(5, active0);
      return 6;
   }
   switch(curChar)
   {
      case 65:
         return jjMoveStringLiteralDfa7_0(active0, 0x100000L);
      case 66:
         return jjMoveStringLiteralDfa7_0(active0, 0x20100L);
      case 97:
         if ((active0 & 0x400000L) != 0L)
            return jjStartNfaWithStates_0(6, 22, 6);
         else if ((active0 & 0x100000000L) != 0L)
            return jjStartNfaWithStates_0(6, 32, 6);
         return jjMoveStringLiteralDfa7_0(active0, 0x4080c400L);
      case 101:
         if ((active0 & 0x8000000L) != 0L)
            return jjStartNfaWithStates_0(6, 27, 6);
         return jjMoveStringLiteralDfa7_0(active0, 0x24000000L);
      case 111:
         return jjMoveStringLiteralDfa7_0(active0, 0x51000L);
      case 112:
         return jjMoveStringLiteralDfa7_0(active0, 0x800L);
      case 113:
         return jjMoveStringLiteralDfa7_0(active0, 0x2000000L);
      case 114:
         return jjMoveStringLiteralDfa7_0(active0, 0x200000200L);
      case 115:
         return jjMoveStringLiteralDfa7_0(active0, 0x2000L);
      case 116:
         return jjMoveStringLiteralDfa7_0(active0, 0x10200000L);
      case 117:
         if ((active0 & 0x400000000L) != 0L)
            return jjStartNfaWithStates_0(6, 34, 6);
         return jjMoveStringLiteralDfa7_0(active0, 0x80080L);
      default :
         break;
   }
   return jjStartNfa_0(5, active0);
}
static private int jjMoveStringLiteralDfa7_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(5, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(6, active0);
      return 7;
   }
   switch(curChar)
   {
      case 67:
         return jjMoveStringLiteralDfa8_0(active0, 0x10000L);
      case 68:
         return jjMoveStringLiteralDfa8_0(active0, 0x4008000L);
      case 97:
         if ((active0 & 0x40000L) != 0L)
            return jjStartNfaWithStates_0(7, 18, 6);
         return jjMoveStringLiteralDfa8_0(active0, 0x200020000L);
      case 98:
         return jjMoveStringLiteralDfa8_0(active0, 0x20000000L);
      case 101:
         if ((active0 & 0x2000L) != 0L)
            return jjStartNfaWithStates_0(7, 13, 6);
         return jjMoveStringLiteralDfa8_0(active0, 0x10000000L);
      case 102:
         return jjMoveStringLiteralDfa8_0(active0, 0x4000L);
      case 105:
         return jjMoveStringLiteralDfa8_0(active0, 0x80000L);
      case 108:
         return jjMoveStringLiteralDfa8_0(active0, 0x100000L);
      case 111:
         if ((active0 & 0x800L) != 0L)
            return jjStartNfaWithStates_0(7, 11, 6);
         return jjMoveStringLiteralDfa8_0(active0, 0x200000L);
      case 112:
         return jjMoveStringLiteralDfa8_0(active0, 0x1000L);
      case 114:
         return jjMoveStringLiteralDfa8_0(active0, 0x800600L);
      case 116:
         return jjMoveStringLiteralDfa8_0(active0, 0x80L);
      case 117:
         if ((active0 & 0x40000000L) != 0L)
            return jjStartNfaWithStates_0(7, 30, 6);
         return jjMoveStringLiteralDfa8_0(active0, 0x2000100L);
      default :
         break;
   }
   return jjStartNfa_0(6, active0);
}
static private int jjMoveStringLiteralDfa8_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(6, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(7, active0);
      return 8;
   }
   switch(curChar)
   {
      case 84:
         return jjMoveStringLiteralDfa9_0(active0, 0xa00000L);
      case 97:
         return jjMoveStringLiteralDfa9_0(active0, 0x104000L);
      case 101:
         if ((active0 & 0x2000000L) != 0L)
            return jjStartNfaWithStates_0(8, 25, 6);
         return jjMoveStringLiteralDfa9_0(active0, 0x80L);
      case 105:
         return jjMoveStringLiteralDfa9_0(active0, 0x10000200L);
      case 108:
         return jjMoveStringLiteralDfa9_0(active0, 0x20000L);
      case 109:
         if ((active0 & 0x80000L) != 0L)
            return jjStartNfaWithStates_0(8, 19, 6);
         break;
      case 111:
         if ((active0 & 0x1000L) != 0L)
            return jjStartNfaWithStates_0(8, 12, 6);
         else if ((active0 & 0x200000000L) != 0L)
            return jjStartNfaWithStates_0(8, 33, 6);
         return jjMoveStringLiteralDfa9_0(active0, 0x4018000L);
      case 114:
         return jjMoveStringLiteralDfa9_0(active0, 0x20000400L);
      case 116:
         return jjMoveStringLiteralDfa9_0(active0, 0x100L);
      default :
         break;
   }
   return jjStartNfa_0(7, active0);
}
static private int jjMoveStringLiteralDfa9_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(7, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(8, active0);
      return 9;
   }
   switch(curChar)
   {
      case 97:
         return jjMoveStringLiteralDfa10_0(active0, 0x20000000L);
      case 99:
         return jjMoveStringLiteralDfa10_0(active0, 0x20000L);
      case 101:
         return jjMoveStringLiteralDfa10_0(active0, 0x200100L);
      case 105:
         return jjMoveStringLiteralDfa10_0(active0, 0x400L);
      case 108:
         if ((active0 & 0x200L) != 0L)
            return jjStartNfaWithStates_0(9, 9, 6);
         return jjMoveStringLiteralDfa10_0(active0, 0x80L);
      case 109:
         return jjMoveStringLiteralDfa10_0(active0, 0x100000L);
      case 111:
         return jjMoveStringLiteralDfa10_0(active0, 0x800000L);
      case 112:
         return jjMoveStringLiteralDfa10_0(active0, 0x10000L);
      case 114:
         if ((active0 & 0x4000L) != 0L)
            return jjStartNfaWithStates_0(9, 14, 6);
         return jjMoveStringLiteralDfa10_0(active0, 0x10000000L);
      case 115:
         return jjMoveStringLiteralDfa10_0(active0, 0x4008000L);
      default :
         break;
   }
   return jjStartNfa_0(8, active0);
}
static private int jjMoveStringLiteralDfa10_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(8, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(9, active0);
      return 10;
   }
   switch(curChar)
   {
      case 97:
         if ((active0 & 0x10000000L) != 0L)
            return jjStartNfaWithStates_0(10, 28, 6);
         return jjMoveStringLiteralDfa11_0(active0, 0x20080L);
      case 98:
         return jjMoveStringLiteralDfa11_0(active0, 0x100000L);
      case 100:
         return jjMoveStringLiteralDfa11_0(active0, 0x20000000L);
      case 101:
         if ((active0 & 0x8000L) != 0L)
            return jjStartNfaWithStates_0(10, 15, 6);
         else if ((active0 & 0x4000000L) != 0L)
            return jjStartNfaWithStates_0(10, 26, 6);
         break;
      case 108:
         if ((active0 & 0x400L) != 0L)
            return jjStartNfaWithStates_0(10, 10, 6);
         return jjMoveStringLiteralDfa11_0(active0, 0x100L);
      case 109:
         return jjMoveStringLiteralDfa11_0(active0, 0x200000L);
      case 110:
         return jjMoveStringLiteralDfa11_0(active0, 0x800000L);
      case 111:
         if ((active0 & 0x10000L) != 0L)
            return jjStartNfaWithStates_0(10, 16, 6);
         break;
      default :
         break;
   }
   return jjStartNfa_0(9, active0);
}
static private int jjMoveStringLiteralDfa11_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(9, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(10, active0);
      return 11;
   }
   switch(curChar)
   {
      case 67:
         return jjMoveStringLiteralDfa12_0(active0, 0x200000L);
      case 97:
         if ((active0 & 0x20000000L) != 0L)
            return jjStartNfaWithStates_0(11, 29, 6);
         return jjMoveStringLiteralDfa12_0(active0, 0x100L);
      case 100:
         return jjMoveStringLiteralDfa12_0(active0, 0x80L);
      case 105:
         return jjMoveStringLiteralDfa12_0(active0, 0x100000L);
      case 111:
         if ((active0 & 0x20000L) != 0L)
            return jjStartNfaWithStates_0(11, 17, 6);
         break;
      case 116:
         return jjMoveStringLiteralDfa12_0(active0, 0x800000L);
      default :
         break;
   }
   return jjStartNfa_0(10, active0);
}
static private int jjMoveStringLiteralDfa12_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(10, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(11, active0);
      return 12;
   }
   switch(curChar)
   {
      case 97:
         if ((active0 & 0x80L) != 0L)
            return jjStartNfaWithStates_0(12, 7, 6);
         return jjMoveStringLiteralDfa13_0(active0, 0x200000L);
      case 100:
         return jjMoveStringLiteralDfa13_0(active0, 0x100L);
      case 111:
         if ((active0 & 0x800000L) != 0L)
            return jjStartNfaWithStates_0(12, 23, 6);
         break;
      case 113:
         return jjMoveStringLiteralDfa13_0(active0, 0x100000L);
      default :
         break;
   }
   return jjStartNfa_0(11, active0);
}
static private int jjMoveStringLiteralDfa13_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(11, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(12, active0);
      return 13;
   }
   switch(curChar)
   {
      case 97:
         if ((active0 & 0x100L) != 0L)
            return jjStartNfaWithStates_0(13, 8, 6);
         break;
      case 110:
         return jjMoveStringLiteralDfa14_0(active0, 0x200000L);
      case 117:
         return jjMoveStringLiteralDfa14_0(active0, 0x100000L);
      default :
         break;
   }
   return jjStartNfa_0(12, active0);
}
static private int jjMoveStringLiteralDfa14_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(12, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(13, active0);
      return 14;
   }
   switch(curChar)
   {
      case 97:
         if ((active0 & 0x200000L) != 0L)
            return jjStartNfaWithStates_0(14, 21, 6);
         break;
      case 101:
         if ((active0 & 0x100000L) != 0L)
            return jjStartNfaWithStates_0(14, 20, 6);
         break;
      default :
         break;
   }
   return jjStartNfa_0(13, active0);
}
static private int jjStartNfaWithStates_0(int pos, int kind, int state)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) { return pos + 1; }
   return jjMoveNfa_0(state, pos + 1);
}
static final long[] jjbitVec0 = {
   0xfffffffffffffffeL, 0xffffffffffffffffL, 0xffffffffffffffffL, 0xffffffffffffffffL
};
static final long[] jjbitVec2 = {
   0x0L, 0x0L, 0xffffffffffffffffL, 0xffffffffffffffffL
};
static private int jjMoveNfa_0(int startState, int curPos)
{
   int startsAt = 0;
   jjnewStateCnt = 21;
   int i = 1;
   jjstateSet[0] = startState;
   int kind = 0x7fffffff;
   for (;;)
   {
      if (++jjround == 0x7fffffff)
         ReInitRounds();
      if (curChar < 64)
      {
         long l = 1L << curChar;
         do
         {
            switch(jjstateSet[--i])
            {
               case 8:
                  if (curChar == 42)
                     { jjCheckNAddStates(0, 2); }
                  else if (curChar == 47)
                  {
                     if (kind > 5)
                        kind = 5;
                     { jjCheckNAdd(9); }
                  }
                  break;
               case 0:
                  if ((0x3ff000000000000L & l) != 0L)
                  {
                     if (kind > 49)
                        kind = 49;
                     { jjCheckNAddStates(3, 5); }
                  }
                  else if (curChar == 47)
                     { jjAddStates(6, 7); }
                  else if (curChar == 34)
                     { jjCheckNAddStates(8, 10); }
                  break;
               case 1:
                  if ((0xfffffffbffffdbffL & l) != 0L)
                     { jjCheckNAddStates(8, 10); }
                  break;
               case 3:
                  if (curChar == 34)
                     { jjCheckNAddStates(8, 10); }
                  break;
               case 4:
                  if (curChar == 34 && kind > 50)
                     kind = 50;
                  break;
               case 6:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 51)
                     kind = 51;
                  jjstateSet[jjnewStateCnt++] = 6;
                  break;
               case 7:
                  if (curChar == 47)
                     { jjAddStates(6, 7); }
                  break;
               case 9:
                  if ((0xffffffffffffdbffL & l) == 0L)
                     break;
                  if (kind > 5)
                     kind = 5;
                  { jjCheckNAdd(9); }
                  break;
               case 10:
                  if (curChar == 42)
                     { jjCheckNAddStates(0, 2); }
                  break;
               case 11:
                  if ((0xfffffbffffffffffL & l) != 0L)
                     { jjCheckNAddStates(0, 2); }
                  break;
               case 12:
                  if (curChar == 42)
                     jjstateSet[jjnewStateCnt++] = 13;
                  break;
               case 13:
                  if ((0xffff7fffffffffffL & l) != 0L)
                     { jjCheckNAddStates(0, 2); }
                  break;
               case 14:
                  if (curChar == 47 && kind > 6)
                     kind = 6;
                  break;
               case 15:
                  if (curChar == 42)
                     jjstateSet[jjnewStateCnt++] = 14;
                  break;
               case 16:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 49)
                     kind = 49;
                  { jjCheckNAddStates(3, 5); }
                  break;
               case 17:
                  if ((0x3ff000000000000L & l) != 0L)
                     { jjCheckNAddTwoStates(17, 18); }
                  break;
               case 18:
                  if (curChar == 46)
                     { jjCheckNAdd(19); }
                  break;
               case 19:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 48)
                     kind = 48;
                  { jjCheckNAdd(19); }
                  break;
               case 20:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 49)
                     kind = 49;
                  { jjCheckNAdd(20); }
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else if (curChar < 128)
      {
         long l = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               case 0:
               case 6:
                  if ((0x7fffffe87fffffeL & l) == 0L)
                     break;
                  if (kind > 51)
                     kind = 51;
                  { jjCheckNAdd(6); }
                  break;
               case 1:
                  if ((0xffffffffefffffffL & l) != 0L)
                     { jjCheckNAddStates(8, 10); }
                  break;
               case 2:
                  if (curChar == 92)
                     jjstateSet[jjnewStateCnt++] = 3;
                  break;
               case 3:
                  if ((0x14400010000000L & l) != 0L)
                     { jjCheckNAddStates(8, 10); }
                  break;
               case 9:
                  if (kind > 5)
                     kind = 5;
                  jjstateSet[jjnewStateCnt++] = 9;
                  break;
               case 11:
               case 13:
                  { jjCheckNAddStates(0, 2); }
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else
      {
         int hiByte = (curChar >> 8);
         int i1 = hiByte >> 6;
         long l1 = 1L << (hiByte & 077);
         int i2 = (curChar & 0xff) >> 6;
         long l2 = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               case 1:
                  if (jjCanMove_0(hiByte, i1, i2, l1, l2))
                     { jjAddStates(8, 10); }
                  break;
               case 9:
                  if (!jjCanMove_0(hiByte, i1, i2, l1, l2))
                     break;
                  if (kind > 5)
                     kind = 5;
                  jjstateSet[jjnewStateCnt++] = 9;
                  break;
               case 11:
               case 13:
                  if (jjCanMove_0(hiByte, i1, i2, l1, l2))
                     { jjCheckNAddStates(0, 2); }
                  break;
               default : if (i1 == 0 || l1 == 0 || i2 == 0 ||  l2 == 0) break; else break;
            }
         } while(i != startsAt);
      }
      if (kind != 0x7fffffff)
      {
         jjmatchedKind = kind;
         jjmatchedPos = curPos;
         kind = 0x7fffffff;
      }
      ++curPos;
      if ((i = jjnewStateCnt) == (startsAt = 21 - (jjnewStateCnt = startsAt)))
         return curPos;
      try { curChar = input_stream.readChar(); }
      catch(java.io.IOException e) { return curPos; }
   }
}

/** Token literal values. */
public static final String[] jjstrLiteralImages = {
"", null, null, null, null, null, null, 
"\141\142\162\145\101\102\165\164\145\154\141\144\141", "\146\145\143\150\141\101\102\165\164\145\154\141\144\141", 
"\141\142\162\145\102\141\162\162\151\154", "\146\145\143\150\141\102\141\162\162\151\154", 
"\141\142\162\145\103\157\160\157", "\146\145\143\150\141\103\157\160\157", "\166\151\162\141\104\157\163\145", 
"\145\156\147\141\162\162\141\146\141\162", "\155\141\151\163\125\155\141\104\157\163\145", 
"\163\145\162\166\145\116\157\103\157\160\157", "\160\145\144\145\116\157\102\141\154\143\141\157", 
"\163\145\104\145\162\102\157\141", "\163\145\104\145\162\122\165\151\155", 
"\155\145\163\164\162\145\101\154\141\155\142\151\161\165\145", "\145\156\161\165\141\156\164\157\124\145\155\103\141\156\141", 
"\164\157\155\141\125\155\141", "\141\164\145\106\151\143\141\162\124\157\156\164\157", 
"\162\157\144\141\144\141", "\141\154\141\155\142\151\161\165\145", 
"\144\145\166\157\154\166\145\104\157\163\145", "\163\145\155\104\157\163\145", 
"\144\157\163\145\111\156\164\145\151\162\141", "\144\157\163\145\121\165\145\142\162\141\144\141", 
"\164\141\116\157\107\162\141\165", "\162\157\164\165\154\157", "\147\141\162\162\141\146\141", 
"\163\151\155\120\141\164\162\141\157", "\156\145\155\101\120\141\165", "\74\75", "\76\75", "\75\75", "\41\75", 
"\46\46", "\174\174", "\53", "\55", "\52", "\57", "\76", "\74", "\41", null, null, null, 
null, null, };
static protected Token jjFillToken()
{
   final Token t;
   final String curTokenImage;
   final int beginLine;
   final int endLine;
   final int beginColumn;
   final int endColumn;
   String im = jjstrLiteralImages[jjmatchedKind];
   curTokenImage = (im == null) ? input_stream.GetImage() : im;
   beginLine = input_stream.getBeginLine();
   beginColumn = input_stream.getBeginColumn();
   endLine = input_stream.getEndLine();
   endColumn = input_stream.getEndColumn();
   t = Token.newToken(jjmatchedKind, curTokenImage);

   t.beginLine = beginLine;
   t.endLine = endLine;
   t.beginColumn = beginColumn;
   t.endColumn = endColumn;

   return t;
}
static final int[] jjnextStates = {
   11, 12, 15, 17, 18, 20, 8, 10, 1, 2, 4, 
};
private static final boolean jjCanMove_0(int hiByte, int i1, int i2, long l1, long l2)
{
   switch(hiByte)
   {
      case 0:
         return ((jjbitVec2[i2] & l2) != 0L);
      default :
         if ((jjbitVec0[i1] & l1) != 0L)
            return true;
         return false;
   }
}

static int curLexState = 0;
static int defaultLexState = 0;
static int jjnewStateCnt;
static int jjround;
static int jjmatchedPos;
static int jjmatchedKind;

/** Get the next Token. */
public static Token getNextToken() 
{
  Token matchedToken;
  int curPos = 0;

  EOFLoop :
  for (;;)
  {
   try
   {
      curChar = input_stream.BeginToken();
   }
   catch(Exception e)
   {
      jjmatchedKind = 0;
      jjmatchedPos = -1;
      matchedToken = jjFillToken();
      return matchedToken;
   }

   try { input_stream.backup(0);
      while (curChar <= 32 && (0x100002600L & (1L << curChar)) != 0L)
         curChar = input_stream.BeginToken();
   }
   catch (java.io.IOException e1) { continue EOFLoop; }
   jjmatchedKind = 0x7fffffff;
   jjmatchedPos = 0;
   curPos = jjMoveStringLiteralDfa0_0();
   if (jjmatchedKind != 0x7fffffff)
   {
      if (jjmatchedPos + 1 < curPos)
         input_stream.backup(curPos - jjmatchedPos - 1);
      if ((jjtoToken[jjmatchedKind >> 6] & (1L << (jjmatchedKind & 077))) != 0L)
      {
         matchedToken = jjFillToken();
         return matchedToken;
      }
      else
      {
         continue EOFLoop;
      }
   }
   int error_line = input_stream.getEndLine();
   int error_column = input_stream.getEndColumn();
   String error_after = null;
   boolean EOFSeen = false;
   try { input_stream.readChar(); input_stream.backup(1); }
   catch (java.io.IOException e1) {
      EOFSeen = true;
      error_after = curPos <= 1 ? "" : input_stream.GetImage();
      if (curChar == '\n' || curChar == '\r') {
         error_line++;
         error_column = 0;
      }
      else
         error_column++;
   }
   if (!EOFSeen) {
      input_stream.backup(1);
      error_after = curPos <= 1 ? "" : input_stream.GetImage();
   }
   throw new TokenMgrError(EOFSeen, curLexState, error_line, error_column, error_after, curChar, TokenMgrError.LEXICAL_ERROR);
  }
}

static void SkipLexicalActions(Token matchedToken)
{
   switch(jjmatchedKind)
   {
      default :
         break;
   }
}
static void MoreLexicalActions()
{
   jjimageLen += (lengthOfMatch = jjmatchedPos + 1);
   switch(jjmatchedKind)
   {
      default :
         break;
   }
}
static void TokenLexicalActions(Token matchedToken)
{
   switch(jjmatchedKind)
   {
      default :
         break;
   }
}
static private void jjCheckNAdd(int state)
{
   if (jjrounds[state] != jjround)
   {
      jjstateSet[jjnewStateCnt++] = state;
      jjrounds[state] = jjround;
   }
}
static private void jjAddStates(int start, int end)
{
   do {
      jjstateSet[jjnewStateCnt++] = jjnextStates[start];
   } while (start++ != end);
}
static private void jjCheckNAddTwoStates(int state1, int state2)
{
   jjCheckNAdd(state1);
   jjCheckNAdd(state2);
}

static private void jjCheckNAddStates(int start, int end)
{
   do {
      jjCheckNAdd(jjnextStates[start]);
   } while (start++ != end);
}

    /** Constructor. */
    public compiladorCachacaScriptTokenManager(SimpleCharStream stream){

      if (input_stream != null)
        throw new TokenMgrError("ERROR: Second call to constructor of static lexer. You must use ReInit() to initialize the static variables.", TokenMgrError.STATIC_LEXER_ERROR);

    input_stream = stream;
  }

  /** Constructor. */
  public compiladorCachacaScriptTokenManager (SimpleCharStream stream, int lexState){
    ReInit(stream);
    SwitchTo(lexState);
  }

  /** Reinitialise parser. */
  
  static public void ReInit(SimpleCharStream stream)
  {


    jjmatchedPos =
    jjnewStateCnt =
    0;
    curLexState = defaultLexState;
    input_stream = stream;
    ReInitRounds();
  }

  static private void ReInitRounds()
  {
    int i;
    jjround = 0x80000001;
    for (i = 21; i-- > 0;)
      jjrounds[i] = 0x80000000;
  }

  /** Reinitialise parser. */
  static public void ReInit(SimpleCharStream stream, int lexState)
  
  {
    ReInit(stream);
    SwitchTo(lexState);
  }

  /** Switch to specified lex state. */
  public static void SwitchTo(int lexState)
  {
    if (lexState >= 1 || lexState < 0)
      throw new TokenMgrError("Error: Ignoring invalid lexical state : " + lexState + ". State unchanged.", TokenMgrError.INVALID_LEXICAL_STATE);
    else
      curLexState = lexState;
  }


/** Lexer state names. */
public static final String[] lexStateNames = {
   "DEFAULT",
};

/** Lex State array. */
public static final int[] jjnewLexState = {
   -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
   -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
   -1, -1, -1, 
};
static final long[] jjtoToken = {
   0xfffffffffff81L, 
};
static final long[] jjtoSkip = {
   0x7eL, 
};
static final long[] jjtoSpecial = {
   0x0L, 
};
static final long[] jjtoMore = {
   0x0L, 
};
    static protected SimpleCharStream  input_stream;

    static private final int[] jjrounds = new int[21];
    static private final int[] jjstateSet = new int[2 * 21];
    private static final StringBuilder jjimage = new StringBuilder();
    private static StringBuilder image = jjimage;
    private static int jjimageLen;
    private static int lengthOfMatch;
    static protected int curChar;
}
